### ISSUE TITLE
Crash of django when reports is big (7.5MO)

### ISSUE THREAD

**Issue by dummys** [cuckoobox/cuckoo#274]
Hi,

I got a crash on django when big reports is created..
Here is the traceback: 

 File "/usr/local/lib/python2.7/dist-packages/django/template/defaulttags.py", line 877, in create_var
    return TemplateLiteral(self.template_parser.compile_filter(value), value)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 360, in compile_filter
    return FilterExpression(token, self)
RuntimeError: maximum recursion depth exceeded

**Comment by rep** [comment]
Sadly we did not have time to work on this, however since it is kind of a lab example and not occurring with real-life samples (malwr.com is doing fine) we will postpone this indefinitely for now. Please open a PR if you're interested in fixing this.

**Comment by jbremer** [comment]
I'm going to assume this issue has already been resolved given all the changes since, one and a half year ago, so closing this issue. Please feel free to re-open or create a new issue if a similar (or other) issue appears.
