### ISSUE TITLE
Add possibility to upload multiple files at once through Django web interface

### ISSUE THREAD

**Issue by botherder** [cuckoobox/cuckoo#297]
Adding multiple files singularly through the web form can be a tedious task.
Would be nice to have a way of uploading multiple files at once and queue them up all with the same provided options.

**Comment by jbremer** [comment]
Anyone who would like to pick up on this feature?

**Comment by chrestme** [comment]
Just for clarification, are you referring to Crashman's request, or the original from @botherder? PR #356 addressed the original request.

**Comment by jbremer** [comment]
As @botherder mentioned this can be done by zipping up the files. I agree that it's sub-optimal, but at this point I don't think it makes sense to do a lot of work on this matter when simply zipping works fine.
And yeah, I mentioned the original request, but it appears it has been resolved already indeed :)

**Comment by KillerInstinct** [comment]
Just FYI, you don't need to use a zip.

Per https://github.com/cuckoobox/cuckoo/blob/master/web/submission/views.py#L58

You can upload multiple files by default which was added with https://github.com/cuckoobox/cuckoo/commit/04b506c2030e67ad20eb65b05f9308de2e6851cb

Just shift-click the files you want to submit and it'll submit 'em.

**Comment by jbremer** [comment]
The zip was for the case where multiple files have to be bundled together for an analysis to work properly :-)

**Comment by KillerInstinct** [comment]
Yeah I read it wrong. Perhaps it would be best to have a "run_this" variable which specifies the actual file to pass to the loader for the zip package.
