### ISSUE TITLE
Path Issue in doc.py and xls.py packages on x64 Guests /w 32bit python

### ISSUE THREAD

**Issue by jhumble** [cuckoobox/cuckoo#301]
Both of these packages enumerate potential locations for the word/excel executables using os.getenv('ProgramFiles'). On 64 bit systems /w 32 bit python, the analyzer ends up running in SysWow64. This causes the following behavior:
getenv('ProgramFiles(x86)') => C:\Program Files (x86)
getenv('ProgramFiles') => C:\Program Files (x86)

The packages mentioned only try 'ProgramFiles' - I point out the getenv('ProgramFiles(x86)' case only because I added that in when attempting a quick fix on my end. 

Regardless, it doesn't pick up the actual location of the word and excel executables which reside in the non-x86 program files directory.

This was on a x64 Windows 7 guest.

The answer here may just be to require 64-bit python on 64-bit guests. I haven't tried that since I didn't want to recreate all of my guests, but I assume it would solve the issue.

**Comment by jbremer** [comment]
The latest and greatest Cuckoo supports 64-bit Python in the `monitor` branch. I have not tested this particular setup yet, but it should work (tm).

**Comment by robertsjw** [comment]
+1

**Comment by jbremer** [comment]
This has been fixed as per #554 / #555.
