### ISSUE TITLE
Machine/Task Correlation when performing a db.fetch

### ISSUE THREAD

**Issue by kholbrook1303** [cuckoobox/cuckoo#302]
There is an issue which has been present for quite some time which I had posted to the community a while back but wanted to log it as a bug.  In the scheduler.py, there is a check for "availables" which is basically just polling the machines table for a count of unlocked machines. This typically is not an issue, but when you send a batch of files to a specific machine (In my case a specific platform), the others will remain unlocked (as they aren't used) which returns ">0", so when the scheduler initiates a db.fetch, it will set all affiliated samples to "running".

**Comment by botherder** [comment]
Should have been fixed with #412
