### ISSUE TITLE
possible missing hook mechanisms

### ISSUE THREAD

**Issue by beast-fighter** [cuckoobox/cuckoo#342]
possible missing hook mechanisms seen within 1.2-dev and Windows 7 VM guest

Using Windows 7 (SP1) x86

Example MD5: 88ab8af8926148df1f8aaaa95f6f8048 (pixpsetup.exe)

Seen within pcap:
GET /components/toolbars/NCH_Chrome.exe HTTP/1.0
Host: www.audiochannel.net

No network api calls seen within behavior section

**Comment by brad-accuvant** [comment]
Very likely this bug, given that the binary has no static imports for wininet.dll: https://github.com/brad-accuvant/cuckoomon-modified/commit/05060e8cda7fb3694cbd73ff799ad2cda24325f5

**Comment by jbremer** [comment]
Assuming that host is still up etc, if you could send me a sample (if you still have it :p), I can test it for you. But with all the improvements this *probably* works now, so I'll just close it.
