### ISSUE TITLE
Unable to Add Tasks with Long File_Types

### ISSUE THREAD

**Issue by jhumble** [cuckoobox/cuckoo#347]
in ./lib/cuckoo/core/database.py the Sample schema defines file_type as a String of max length 255. However, doc files will occasionally have file_types exceeding 255 characters (see below).

We never noticed an issue before when we were using MySQL because it will just truncate the string at 255 chars. However, we recently switched over to Postgres, and it will actually throw an error, preventing the file from making it into the db and being analyzed. 

$ file ~/breaks_cuckoo.file
breaks_cuckoo.file: Composite Document File V2 Document, Little Endian, Os: Windows, Version 5.1, Code page: 949, Author: Tran Duy Linh, Template: Normal.dotm, Last Saved By: Tran Duy Linh, Revision Number: 2, Name of Creating Application: Microsoft Office Word, Total Editing Time: 04:00, Create Time/Date: Fri Nov 23 04:35:00 2012, Last Saved Time/Date: Fri Nov 23 04:39:00 2012, Number of Pages: 1, Number of Words: 5, Number of Characters: 34, Security: 0

**Comment by jekil** [comment]
This issue was closed, file type field is now Text()
