### ISSUE TITLE
Long processing of samples caused by large raw logs

### ISSUE THREAD

**Issue by Thorsten-Sick** [cuckoobox/cuckoo#365]
Some Samples (especially Adware) cause large raw API logs. Processing those wastes minutes to hours. The resulting json is about 300 MB large. There is an option to not process large logs at all, good, but not perfect.
But a second option to restrict the number of processed API calls for each process would reduce processing time and result size. And we would have at least something in the logs, just not everyting.

**Comment by jbremer** [comment]
Sorry, but as mentioned in the closed PR.. should probably not go down this road.
