### ISSUE TITLE
Cucko processes/api section missing things process monitor sees.

### ISSUE THREAD

**Issue by TheInternetIsReal** [cuckoobox/cuckoo#373]
Hello,

First of all, I love using Cuckoo! The processes section along with automation and ease of use opens up a whole new world for writing host based IDS/IPS rules.

That said, I believe Cuckoo is missing API calls or behaviors that process monitor (another api style logger) is seeing. I'm not entirely sure how these two different tools align and what they look for, but for what it's worth, Cuckoo is missing some (crucial) things.

**Example using mimikatz.exe -----------------------------------------------------------------------**

**Procmon sees this exact behavior around some dlls when mimikatz is simply opened via double clicking. This is specifically for vaultcli.dll:**

"Time of Day","Process Name","PID","Operation","Path","Result","Detail","Date & Time","Event Class","Sequence","Image Path","Description","User","Command Line","TID","Parent PID"

**"11:17:11.7545168 AM","mimikatz.exe","2796","CreateFile"**,"C:\Users\Administrator\Desktop\malware and cred dumpers\mimikatz cred dumper\mimikatz cred dumper\vaultcli.DLL","NAME NOT FOUND","Desired Access: Read Attributes, Disposition: Open, Options: Open Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a","8/13/2014 11:17:11 AM","File System","n/a",

**"11:17:11.7546235 AM","mimikatz.exe","2796","CreateFile"**,"C:\Windows\System32\vaultcli.dll","SUCCESS","Desired Access: Read Attributes, Disposition: Open, Options: Open Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a, OpenResult: Opened","8/13/2014 11:17:11 AM","File System","n/a",

**"11:17:11.7546763 AM","mimikatz.exe","2796","QueryBasicInformationFile"**,"C:\Windows\System32\vaultcli.dll","SUCCESS","CreationTime: 7/13/2009 7:37:00 PM, LastAccessTime: 7/13/2009 7:37:00 PM, LastWriteTime: 7/13/2009 9:16:17 PM, ChangeTime: 5/9/2013 2:13:18 PM, FileAttributes: A","8/13/2014 11:17:11 AM","File System","n/a",

**"11:17:11.7546853 AM","mimikatz.exe","2796","CloseFile"**,"C:\Windows\System32\vaultcli.dll","SUCCESS","","8/13/2014 11:17:11 AM","File System","n/a",

**"11:17:11.7547635 AM","mimikatz.exe","2796","CreateFile"**,"C:\Windows\System32\vaultcli.dll","SUCCESS","Desired Access: Read Data/List Directory, Execute/Traverse, Synchronize, Disposition: Open, Options: Synchronous IO Non-Alert, Non-Directory File, Attributes: n/a, ShareMode: Read, Delete, AllocationSize: n/a, OpenResult: Opened","8/13/2014 11:17:11 AM","File System","n/a",

**"11:17:11.7550459 AM","mimikatz.exe","2796","CreateFileMapping**","C:\Windows\System32\vaultcli.dll","FILE LOCKED WITH ONLY READERS","SyncType: SyncTypeCreateSection, PageProtection: PAGE_EXECUTE","8/13/2014 11:17:11 AM","File System","n/a",

**"11:17:11.7551046 AM","mimikatz.exe","2796","CreateFileMapping"**,"C:\Windows\System32\vaultcli.dll","SUCCESS","SyncType: SyncTypeOther","8/13/2014 11:17:11 AM","File System","n/a",

**"11:17:11.7551920 AM","mimikatz.exe","2796","Load Image"**,"C:\Windows\System32\vaultcli.dll","SUCCESS","Image Base: 0x73810000, Image Size: 0xc000","8/13/2014 11:17:11 AM","Process","n/a",

**"11:17:11.7552049 AM","mimikatz.exe","2796","CloseFile"**,"C:\Windows\System32\vaultcli.dll","SUCCESS","","8/13/2014 11:17:11 AM","File System","n/a",

**Cuckoo, on the other hand, ONLY sees this:**

LdrLoadDll --- Flags => 1244304 BaseAddress => 0x70a80000 FileName => vaultcli --- SUCCESS ---  0x00000000

Not sure if this is intended, but the information provided by procmon is crucial to my work. I'd rather go to one place instead of two ;)

Finally, something else that is troubling to me is that the same behavior which happens for vaultcli.dll seen in procmon above also happens for MANY other dlls, such as samlib.dll. _Cuckoo does not report ANY API calls for samlib.dll and some others_, not even the LdrLoadDLL one.

**Comment by jbremer** [comment]
Postponed this bug - it'll be fixed as part of various other improvements for version 1.3

**Comment by jbremer** [comment]
This is going to require some more testing probably, but this issue should've been fixed in the following commit (followed by a unittest). https://github.com/jbremer/monitor/commit/68e20deabecb4cd7b0a22c388ad9bd0a0ff2525f https://github.com/jbremer/monitor/commit/360ed4980e0123156f92689899f8d88cd4f4d120
