### ISSUE TITLE
Excel file getting no package

### ISSUE THREAD

**Issue by dewiestr** [cuckoobox/cuckoo#389]
I'm currently getting the wrong package assignment ( the default one) for excel files without extensions.

Can this be confirmed ?

**Comment by jekil** [comment]
@dewiestr can you please provide some feedback? thanks

**Comment by jekil** [comment]
@dewiestr without a test case sample we are unable to reproduce your issue

**Comment by botherder** [comment]
Closed until the submitted provides more information.

**Comment by dewiestr** [comment]
Actually this is solved because the line 30 of analyzer/windows/lib/core/packages.py was changed to:

elif "Microsoft Office Excel" in file_type or "Microsoft Excel" in file_type  or file_name.endswith((".xls", ".xlsx")):
