### ISSUE TITLE
No behavior logs when process_results is disabled

### ISSUE THREAD

**Issue by botherder** [cuckoobox/cuckoo#390]
If process_results is set to Off in cuckoo.conf, there are no .bson behavior logs generated and therefore the reports are empty.

**Comment by jekil** [comment]
Now seems to work (i mean it creates .bson files)

**Comment by rep** [comment]
It was not directly related to process_results - but as @jekil mentioned it is not happening anymore anyways. I assume it was a buggy commit which has since been reworked / fixed.

Closing.
