### ISSUE TITLE
Fix the check on permissions on tcpdump

### ISSUE THREAD

**Issue by botherder** [cuckoobox/cuckoo#423]
As I merged the fix from @brad-accuvant on `sniffer.py`, the module isn't actually working anymore.

The following isn't actually working when tcpdump is enabled through the use of the `setcap` command:
    mode = os.stat(tcpdump)[stat.ST_MODE]
    if (mode & stat.S_ISUID) == 0:

We need to devise a way to make this permissions check both for suid and cap enabled tcpdumps.

**Comment by rep** [comment]
Nothing we should fix in cuckoo code. Could be mentioned in the documentation maybe. We could supply a launcher shell script that takes care of some of the environment stuff maybe, but imho this shouldn't live in python side.

**Comment by rep** [comment]
Added a paragraph, I think that should cover it. The code should just assume the user has followed the docs and execute tcpdump. If it fails, warn the user. I would remove the other checks around it.
