### ISSUE TITLE
Warning: Cannot allocate Memory : Virtual box shuts off

### ISSUE THREAD

**Issue by efnunes** [cuckoobox/cuckoo#433]
Hi,
I was able to schedule and run many malware samples without any issues on cuckoo. But now I get a warning :
1.Unable to stop machine windows: VBoxManage failed powering off the machine: [Errno 12] Cannot allocate memory 
2. VBoxManage failed to check status for machine windows: [Errno 12] Cannot allocate memory
After this the virtual box just shuts off , and no further analysis takes place. If I restart cuckoo, everything works fine , but again after analyzing few samples the same error happens.
Any help would be appreciated.

Thanks,
Eric

**Comment by botherder** [comment]
Might it be that you're running out of memory?
Set the max_analysis_count to like 10 and have a runit script that keeps Cuckoo running.

**Comment by efnunes** [comment]
I figured it out, there were some issues with the guest additions , since I changed the path of the windows image file , it was not able to find it. I changed the path and that fixed it .
