### ISSUE TITLE
Non-general connection to SQL

### ISSUE THREAD

**Issue by wbenny** [cuckoobox/cuckoo#437]
It's not possible to use any other SQL engine but SQLite after this commit: https://github.com/cuckoobox/cuckoo/commit/9ac01a2cc8bde8fe8891ec0c19e3eeb021e93e6d , since "check_same_thread" is SQLite-specific.

**Comment by rep** [comment]
we know, yeah - it's about to be generalized. thanks for creating the issue for it!

**Comment by jekil** [comment]
Now "check_same_thread" is used only if dbms is sqlite
