### ISSUE TITLE
cuckoo crashes on nested archive

### ISSUE THREAD

**Issue by chipitsine** [cuckoobox/cuckoo#440]
https://yadi.sk/d/OKmYKd_me6KzC - "sweeteners.zip" containing sweeteners.zip inside.
cuckoo dies

**Comment by jekil** [comment]
Confirmed, thanks for reporting.

**Comment by chipitsine** [comment]
I tried nested zip on http://malwr.com

https://malwr.com/analysis/MTcwYWE3NDVhMDAxNGY2NjkwYjZjY2ZlNjliZTA1Nzk/

it failed. is malwr.com still running old cuckoo ?

another question, I've looked through the code, I've no idea how it would behave if we encounter

1.zip --> 2.zip --> 1.zip --> 1.exe

so, maybe it's better not to check whether there nested zip, but extract zip into uniq (guid based name) folder ?

**Comment by jekil** [comment]
The purpose of the zip package is not to deal with all possible configurations but to give a way to upload a sample which needs other files (i.e. dlls to run), all zipped in an archive.
Anyway i think it could work because the unzip is recursive, although i never tried.

**Comment by KillerInstinct** [comment]
@jekil does the zip package actually extract more than one file? 

`file_name = zipinfos[0].filename`

Seems to indicate we only take one file -- not sure how having multiple files would be possible. It may be better to introduce a multipart analysis package which extracts all contents to a folder and executes a user specified file (Error out if not provided). Then it would keep the zip analysis package for analyzing .zip files or packages where people share using password protected zips.
