### ISSUE TITLE
zip file analysis problem

### ISSUE THREAD

**Issue by oklimemilko** [cuckoobox/cuckoo#459]
I submitted a .zip archive for analysis and I get the following error:

2015-01-22 14:28:35,613 [lib.cuckoo.core.scheduler] ERROR: Analysis failed: The package "modules.packages.zip" start function raised an error: Unable to execute the initial process, analysis aborted.

OS: Debian GNU/Linux 7 (wheezy)
Linux cuckoo-server 3.2.0-4-amd64 #1 SMP Debian 3.2.63-2+deb7u1 x86_64 GNU/Linux
Cuckoo Sandbox 1.2-dev
I tested other version 0.5 - 1.2 -dev. I had same problem.

**Comment by jekil** [comment]
Thanks for reporting. It depends from the zip. Could you give more information?

**Comment by oklimemilko** [comment]
what else you need ?

**Comment by jekil** [comment]
Do you tested on latest master release? Could you (privately by mail) share the sample?

**Comment by oklimemilko** [comment]
yes I could. Please give me your email address, or send mail for me.

**Comment by chriscard9** [comment]
ots still npt shire if I jave it enuff.time to let it roll
On Feb 5, 2015 12:15 PM, "Alessandro Tanasi" <notifications@github.com>
wrote:
>
> Do you tested on latest master release? Could you (privately by mail)
share the sample?

**Comment by jekil** [comment]
@oklimemilko alessandro@lonerunners.net (thanks a lot)

**Comment by jekil** [comment]
As report by mail, the sample contains only a text file.

**Comment by piazzamp** [comment]
@jekil should there be a check for executability before the [last line of zip.py](https://github.com/cuckoobox/cuckoo/blob/1223a497111e7de84d0536a8e9f422bcfb1ca5b9/analyzer/windows/modules/packages/zip.py#L97)? ie: `os.access(file_path. os.X_OK)`
or, better yet, recursive analysis of the uncompressed file using the appropriate package?

**Comment by ramidon45** [comment]
Hi, I have the same problem with the zip package. Have you got a solution?
Thank you

Thomas
