### ISSUE TITLE
Database error

### ISSUE THREAD

**Issue by supahal** [cuckoobox/cuckoo#462]
DEBUG:lib.cuckoo.core.database:Database error viewing task: (OperationalError) (2006, 'MySQL server has gone away') 'SELECT tasks.id AS tasks_id, tasks.targe
t AS tasks_target, tasks.category AS tasks_category, tasks.timeout AS tasks_timeout, tasks.priority AS tasks_priority, tasks.custom AS tasks_custom, tasks.ma
chine AS tasks_machine, tasks.package AS tasks_package, tasks.options AS tasks_options, tasks.platform AS tasks_platform, tasks.memory AS tasks_memory, tasks
.enforce_timeout AS tasks_enforce_timeout, tasks.clock AS tasks_clock, tasks.added_on AS tasks_added_on, tasks.started_on AS tasks_started_on, tasks.complete
d_on AS tasks_completed_on, tasks.status AS tasks_status, tasks.sample_id AS tasks_sample_id \nFROM tasks \nWHERE tasks.id = %s' (1L,)
ERROR:root:Exception when processing task ID 1.
Traceback (most recent call last):
  File "./process.py", line 57, in autoprocess
    ar.get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 558, in get
    raise self._value
AttributeError: 'NoneType' object has no attribute 'to_dict'
DEBUG:lib.cuckoo.core.database:Database error setting status: (DataError) (1265, "Data truncated for column 'status' at row 1") 'UPDATE tasks SET status=%s W
HERE tasks.id = %s' ('failed_processing', 1L)
INFO:root:Processing analysis data for Task #1 

Info:
mysql  Ver 14.14 Distrib 5.5.41, for debian-linux-gnu (x86_64) using readline 6.3

Test case:
1. cuckoo.py --clean
2. process_results = off

**Comment by jekil** [comment]
The error "MySQL server has gone away" is typical when there are issues with mysql server (i.e. server down, process restarting), could you check please?

**Comment by XayOn** [comment]
Same thing as I recently commented on your other bug: https://github.com/cuckoobox/cuckoo/issues/467

Adding those status to the enum in the mysql database should fix it for you. Or fixing database.py and doing a database migration

**Comment by rep** [comment]
Should be fixed / solved with our commits related to the status enum and the updated locking on Database().

Please re-open if the problem occurs again after 1.2 release.
