### ISSUE TITLE
CuckooCriticalError: Please update your configuration. Unable to shut 'cuckoo' down or find the mach...

### ISSUE THREAD

**Issue by mist3r0** [cuckoobox/cuckoo#465]
I created an Ubuntu-14.04.1-desktop-amd64 VM on my Laptop [Network Conf. NAT (IP: 192.168.255.128/24)] using VMware.

Within Ubuntu I installed VirtualBox and I created a Windows XP VM. [Network Conf. HOST-Only: IP 192.168.56.101]

Ubuntu VM and Windows XP are able to ping each other.

But when I try to run Cuckoo i receive the following error:

[root] CRITICAL: CuckooCriticalError: Please update your configuration. Unable to shut 'cuckoo' down or find the machine in its proper state: Timeout hit while for machine cuckoo to change status

I do not understand what is the problem. Someone could help me?

**Comment by jekil** [comment]
You probably did a wrong setup, please check the documentation again, if the issue persist please use community platform. (This issue tracker is only for bugs)

**Comment by mist3r0** [comment]
Ciao Alessandro,

ho seguito la guida passo passo.
Il problema potrebbe essere una doppia virtualizzazione?
Sapresti darmi qualche consiglio relativo a quale parte delle
configurazione ricontrollare?

Saluti,
Il 05/feb/2015 00:57 "Alessandro Tanasi" <notifications@github.com> ha
scritto:
