### ISSUE TITLE
Virustotal module freeze if used in process.py

### ISSUE THREAD

**Issue by jekil** [cuckoobox/cuckoo#466]
Urllib2 call in virustotal module il blocking and freeze when called with apply_async(). It needs investigation.

**Comment by jekil** [comment]
It happens only on Mac (yosemite)

**Comment by rep** [comment]
Push to 1.3, we don't have any additional info and no easy way right now to test with Mac. Can't reproduce anywhere else.

**Comment by jbremer** [comment]
Due to some changes VirusTotal is now queries through the use of the `requests` library, deprecating this issue.
