### ISSUE TITLE
Disabling rescheduling adds inestability

### ISSUE THREAD

**Issue by XayOn** [cuckoobox/cuckoo#470]
Rescheduling is used so that if cuckoo is killed or shut down in the middle of an analysis it can recover the task and restart it on restart.
The thing is, if you disable it, the tasks will be in "running" state forever.
That's kind of the expected result, but either way:
- Doc is not clear enough on that
- It's probably to be changed.

I think the correct way is to start using FAILED_ANALYSIS status, that is currently used on process.py only, and it's not being correctly applied to the database (it's not on the states enum), and 

if not cfg.reschedule:
   db.set_status(task.id,  FAILED_ANALYSIS)

I can do a patch for this, if it's decided to go this way.
There probably are better solutions to this.

**Comment by jekil** [comment]
Thanks a lot for reporting it.

**Comment by rep** [comment]
Was implemented, on startup without reschedule the task status gets set to FAILED_ANALYSIS.
