### ISSUE TITLE
'analysis_tags' is not a valid tag library: ImportError raised loading 

### ISSUE THREAD

**Issue by doomedraven** [cuckoobox/cuckoo#473]
Error during template rendering

In template cuckoo/web/templates/analysis/overview/_signatures.html, error at line 1
'analysis_tags' is not a valid tag library: ImportError raised loading analysis.templatetags.analysis_tags: No module named hexdump
1 	{% load analysis_tags %}
2 	
3 	<style type="text/css">
4 	.signature {
5 	padding: 5px;
6 	padding-left: 10px;
7 	margin-bottom: 5px;
8 	}
9 	
10 	.signature-process {
11 	background-color: #d9edf7;

**Comment by brad-accuvant** [comment]
pip install hexdump

**Comment by doomedraven** [comment]
@brad-accuvant  thanks, work :D

**Comment by jekil** [comment]
hexdump was removed and not required now
