### ISSUE TITLE
pool.py ERROR when running the processing.py (mySQL)

### ISSUE THREAD

**Issue by mhanne0915** [cuckoobox/cuckoo#475]
Running processing.py separately produces the error below when using mySQL database.
mySQL version: mysql  Ver 14.14 Distrib 5.5.41, for debian-linux-gnu (x86_64) 
command: ./processing.py auto -p 5

Infinite ERROR:
Traceback (most recent call last):
  File "./process.py", line 58, in autoprocess
    ar.get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 558, in get
    raise self._value
AssertionError

**Comment by jekil** [comment]
thanks for reporting, could you please try after a git pull?

**Comment by mhanne0915** [comment]
thanks jekil, it's really fixed the AssertionError. Though the report generation has been completed, i still got a warning and error. See below ( just looking now on previous issues, if this problem was already fixed or mentioned) :

WARNING:sqlalchemy.pool.QueuePool:Error closing cursor: (2014, "Commands out of sync; you can't run this command now")
INFO:root:Processing analysis data for Task #1
ERROR:root:Exception when processing task ID 1.
Traceback (most recent call last):
  File "./process.py", line 58, in autoprocess
    ar.get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 558, in get
    raise self._value
AttributeError: 'NoneType' object has no attribute 'to_dict'

**Comment by jekil** [comment]
yeah i noticed that a couple of days ago and i am working on it to fix it in the better way

**Comment by mhanne0915** [comment]
oh i see. thanks again:)

**Comment by jekil** [comment]
I opened #476 so you are able to keep track of the status of the second bug

**Comment by mhanne0915** [comment]
ok got it :+1: thanks

**Comment by rep** [comment]
We made some changes to the database connection locking for multiprocessing and thus this problem should be fixed. We did test latest trunk against MySQL and it works with parallel processing.

Closing the ticket, please re-open if the problem persists.

**Comment by mhanne0915** [comment]
Thanks rep:)
