### ISSUE TITLE
Error in process.py with mysql

### ISSUE THREAD

**Issue by jekil** [cuckoobox/cuckoo#476]
As reported in #475 :

WARNING:sqlalchemy.pool.QueuePool:Error closing cursor: (2014, "Commands out of sync; you can't run this command now")
INFO:root:Processing analysis data for Task #1
ERROR:root:Exception when processing task ID 1.
Traceback (most recent call last):
File "./process.py", line 58, in autoprocess
ar.get()
File "/usr/lib/python2.7/multiprocessing/pool.py", line 558, in get
raise self._value
AttributeError: 'NoneType' object has no attribute 'to_dict'

**Comment by rep** [comment]
We made some changes to the database connection locking for multiprocessing and thus this problem should be fixed. We did test latest trunk against MySQL and it works with parallel processing.

Closing the ticket, please re-open if the problem persists.
