### ISSUE TITLE
[dist.py] VARCHAR requires a length on dialect mysql

### ISSUE THREAD

**Issue by mhanne0915** [cuckoobox/cuckoo#477]
Im trying to setup distributed cuckoo, however when i put DB connection as my parameter, I got this error:

-----------ERROR-------
Traceback (most recent call last):
  File "./dist.py", line 635, in <module>
    app = create_app(database_connection=args.db)
  File "./dist.py", line 597, in create_app
    db.create_all()
.....
....
....
sqlalchemy.exc.CompileError: (in table 'machine', column 'tags'): VARCHAR requires a length on dialect mysql
--------ERROR END-------

Im not sure if this is the right fix, but to fix this in my end, I modified the dist.py [line 64]:
    impl = db.String ->     impl = db.Text

**Comment by jbremer** [comment]
You're right, thanks for the bug report.

**Comment by mhanne0915** [comment]
youre welcome jbremer :)
