### ISSUE TITLE
distributed cuckoo - IOError: No such file or directory [machine 2]

### ISSUE THREAD

**Issue by mhanne0915** [cuckoobox/cuckoo#478]
I setup distributed cuckoo (3 machines), i followed everything that has been written in the guide here: http://cuckoo.readthedocs.org/en/latest/usage/dist/#quick-usage

dist machine - host the mySQL server (cuckoo db) and runs dist.py, 
machine 1 - only a cuckoo node (runs api.py, cuckoo.py and process.py) 
machine 2 - only a cuckoo node (runs api.py, cuckoo.py and process.py)
machines 1 and 2 both have one guest machine each.

for both cuckoo.conf, the DB connections are pointed to the mySQL server (cuckoo db), which is the ip of dist machine. I also turned off the processing in the cuckoo.conf.

-------RESULT after submitting 2 samples to analyze------

machine 1:
cuckoo.py - <task=2> has been processed properly

machine 2:

[lib.cuckoo.core.scheduler] INFO: Starting analysis of FILE "/tmp/cuckoo-tmp/upload_Wn0Iyy/tmpw05od4" (task=1) 2015-02-21 15:18:53,784 [lib.cuckoo.core.scheduler] ERROR: Failure in AnalysisManager.run
.....
.....
IOError: [Errno 2] No such file or directory: '/tmp/cuckoo-tmp/upload_hOUzJ2/tmp86uvmd'

**Comment by jbremer** [comment]
Each machine should have its own database. So either use "cuckoo1" and "cuckoo2" databases for the respective machines or have a localhost database on each machine.

Let me know if that works for you.

**Comment by mhanne0915** [comment]
hi jbremer, it works :100:  thanks so much for the help.
