### ISSUE TITLE
Django Web Interface for Distributed Cuckoo

### ISSUE THREAD

**Issue by mhanne0915** [cuckoobox/cuckoo#482]
I setup a distributed cuckoo. i have 12 cuckoo nodes and 1 node for dist.py. I run the manage.py of dist.py and it seems that it doesnt work. Is django web interface (manage.py)  built for non distributed cuckoo only? Do you  guys have a plan to have a web interface (django) for distributed cuckoo?

**Comment by jbremer** [comment]
Hi,

I've developed dist.py for personal usage - it's not yet in a production state. If you have particular bugs that need to be solved let me know, otherwise for now my suggestion for now is wait until it's "officially" released. Or I can keep you in the loop personally if you like. I expect it to be production ready for version 1.3.
12 nodes - how many VMs each?

Jurriaan

**Comment by mhanne0915** [comment]
Id love it if you keep me in the loop ;) So far, 20VMs per node runs smoothly. I'll try to increase it to 30 and see if the machine can still handle it. Ill let you know if I found a bug :) have a nice day~ Thanks

**Comment by jbremer** [comment]
`dist.py` has since been moved to the `distributed` directory, but still no decent Web interface or Dashboard ;) Feel free to add one yourself or alternatively contact me if you are really interested.
Closing this issue for now as otherwise I don't see a Web interface coming up soon anyway.

**Comment by jhg** [comment]
So interesting, 240 MV. How work now `dist.py`? What is next item in ToDo about it? Reports is storage in each node, in master, DB? I like it.

**Comment by mhanne0915** [comment]
@jbremer, thanks for letting me now about the status. I'll let you know if i get any improvements on dist.py. Thanks.

@jhg, right now dist.py is doing fine. Im just storing all the logs(htm logs, json, binaries etc) in my NAS server and just let me team mates download the logs for them to see the results. hehehe. I'm not so familiar with the django/web based programming and the mongodb. i need a little time to study them first.
Actually the problem right now in distributed is, it doesn't have Django web interface, and we need the reports should be placed in one mongodb.
