### ISSUE TITLE
Droped file wrong html table tag

### ISSUE THREAD

**Issue by dingyuchi** [cuckoobox/cuckoo#488]
https://github.com/cuckoobox/cuckoo/blob/master/web/templates/analysis/dropped/index.html

    <tr>
        <th>File Size</th>
        <td>{{file.size}} bytes</th>
    </tr>
    ....
    <tr>
        <th>Ssdeep</th>
        <td>{{file.ssdeep}}</th>
    </tr>

`<td></td>` not `<td></th>`

**Comment by jekil** [comment]
Thanks for reporting it.
