### ISSUE TITLE
Old version constant 1.2-dev

### ISSUE THREAD

**Issue by r00t0vi4** [cuckoobox/cuckoo#489]
In http://downloads.cuckoosandbox.org/1.2/cuckoo_1.2.tar.gz old version constant  (1.2-dev). Must be 1.2. (see "cuckoo/lib/cuckoo/common/constants.py" )

**Comment by rodionovd** [comment]
Should be fixed with https://github.com/cuckoobox/cuckoo/commit/5231ff3a455e9c1c36239a025a1f6840029a9ed8

**Comment by jekil** [comment]
Thanks for reporting.
