### ISSUE TITLE
To do: Add localization in templates

### ISSUE THREAD

**Issue by r00t0vi4** [cuckoobox/cuckoo#492]
I think will be comfortably with native language in web interface.
I request adding localization files in cuckoo. Community will translate for all languages.
For example:
![2015-03-06_094057](https://cloud.githubusercontent.com/assets/3502081/6523145/f0fe7426-c3e4-11e4-9cb2-bad60c03ff55.png)

**Comment by rep** [comment]
Appreciate the offer and idea, however I'm not sure we are really interested in localization. It will be a weird mix of local + english anyways with all the special terms. I'm not a native english speaker myself and I would never ever want to switch my Cuckoo interface / report language.

We'll discuss it.

**Comment by r00t0vi4** [comment]
OK. My next idea - create double-panel additional form (picture above). On small screens panel not fit. Maybe create new issue? Or create pull request?

**Comment by jbremer** [comment]
@r00t0vi4 Feel free to create pull requests for such ideas (double-panel form)! But as outlined by @rep we're not interested in keeping up with localization at this time as this will require quite some effort in the future to keep up with. (Besides the fact that I wouldn't even want to use Cuckoo in my native language, Dutch, and I guess this is the same for many other countries, except maybe French people).

**Comment by r00t0vi4** [comment]
I found some tips to add localization in cuckoo:
http://valentinbourgoin.net/blog/article/internationaliser-application-django-multilingual-ng/

Adding localizaton in template very simple:
{% trans "Translation" %}
