### ISSUE TITLE
Network Analysis failure

### ISSUE THREAD

**Issue by The-Betrayer** [cuckoobox/cuckoo#494]
Hi,

 I've installed Cuckoo 1.2 on Ubuntu 14.04 (and later upgraded to 14.10) and I'm getting the same error (below) to any sample I'm using:

2015-03-07 00:39:49,580 [lib.cuckoo.core.plugins] ERROR: Failed to run the processing module "NetworkAnalysis":
Traceback (most recent call last):
  File "/home/alex/cuckoo/lib/cuckoo/core/plugins.py", line 186, in process
    data = current.run()
  File "/home/alex/cuckoo/modules/processing/network.py", line 596, in run
    results = Pcap(pcap_path).run()
NameError: global name 'pcap_path' is not defined

Any ideas how I can troubleshoot this?

Thank you,
Alex.

**Comment by r00t0vi4** [comment]
Maybe you set timeout < 30 seconds?

**Comment by The-Betrayer** [comment]
Thank you r00t0vi4 but the error doesn't seem to be related to a timeout. I'm using the default timeouts.

**Comment by The-Betrayer** [comment]
Interesting enough, I was monitoring the file level activity with iwatch and I don't see a pcap file created. Is this normal?

**Comment by jekil** [comment]
Thanks for reporting it. The bug was introduced it e656843f0f4593c63203eb9ffbf938b61f1d1d22 and it was related to a typo.
