### ISSUE TITLE
YARA signatures not reporting

### ISSUE THREAD

**Issue by johnc-ncc** [cuckoobox/cuckoo#498]
Current Cuckoo git release;
Yara 3.2.0;

If Cuckoo reports a warning about a Yara rule eg:

2015-03-16 10:53:35,094 [lib.cuckoo.common.objects] WARNING: Unable to match Yara signatures: /opt/cuckoo/data/yara/binaries/test.yara(74): $opcodes04 is slowing down scanning

No results are displayed in the Yara section on the analysis results.
I have tested this rule manually using Yara and it works fine.

**Comment by botherder** [comment]
Perhaps the rule on yara-python is causing issues. Can you share the rule?

**Comment by johnc-ncc** [comment]
Yep heres an example rule:

///////////////////////////////////////////////////////////////////////

rule test_rule_1 {
        meta:
                author = "John"
                description = "Test Rule 1"
        condition:
                uint16(0) == 0x5A4D and uint32(uint32(0x3C)) == 0x00004550
}

rule test_rule_2 {
        meta:
                author = "John"
                description = "Test Rule 2"
        strings:
                $opcodes01 = { AA BB CC DD AA BB CC DD AA BB CC DD AA BB }
                $opcodes02 = { DD CC BB AA DD CC BB AA DD BB CC AA DD CC }
                $opcodes03 = { E8 ?? ?? 00 00 C7 44 ?? ?? ?? ?? 00 00 C7 44 ?? ?? ?? ?? ?? 00 89 ?? ?? E8 ?? ?? ?? 00 }
        condition:
                2 of them
}

///////////////////////////////////////////////////////////////////////

test_rule_1 is a executable check.
test_rule_2 is a modified version of one of my rules which cause the problem.

Using normal YARA against a executable, alerts on rule 1, and warns that rule 2 is slowing down scanning.
Using Cuckoo, no rules are alerted on.

**Comment by botherder** [comment]
I removed Yara's error on warning. This should allow the results for the other rules to be displayed.
You should however investigate on what is causing the performance slow-down.
