### ISSUE TITLE
Inquiry: Do you encounter this issue when cuckoo runs tcpdump (having non-root user)?

### ISSUE THREAD

**Issue by supahal** [cuckoobox/cuckoo#501]
tcpdump: eth0: You don't have permission to capture on that device

**Comment by gaelmuller** [comment]
This is a normal error, and the current documentation should prevent against it:

https://cuckoo.readthedocs.org/en/latest/installation/host/requirements/#installing-tcpdump

It says that you should set specific capabilities on the binary:

```
$ sudo setcap cap_net_raw,cap_net_admin=eip /usr/sbin/tcpdump
```

**Comment by jekil** [comment]
As @gaelmuller said, it is not a bug but a point in the documentation you probably miss. I am closing this issue. Feel free to re-open it if you have more in-topic requests.

**Comment by supahal** [comment]
Shoot. Thank you for the help.
