### ISSUE TITLE
Comparing URLs causes an exception

### ISSUE THREAD

**Issue by lhaagsma** [cuckoobox/cuckoo#504]
When clicking 'Compare' on a URL report the following error appears: 

    KeyError at /compare/12/
    'file' 
    Request Method:	GET
    Request URL:	http://localhost:8000/compare/12/
    Django Version:	1.7.7
    Exception Type:	KeyError
    Exception Value:	
    'file'
    Exception Location:	/home/cuckoo/cuckoo/web/compare/views.py in left, line 31
    Python Executable:	/usr/bin/python
    Python Version:	2.7.3
    Python Path:	
    ['/home/cuckoo/cuckoo/web',
    '/usr/lib/python2.7',
    '/usr/lib/python2.7/plat-linux2',
    '/usr/lib/python2.7/lib-tk',
    '/usr/lib/python2.7/lib-old',
    '/usr/lib/python2.7/lib-dynload',
    '/usr/local/lib/python2.7/dist-packages',
    '/usr/lib/python2.7/dist-packages',
    '/usr/lib/pymodules/python2.7',
    '/home/cuckoo/cuckoo/web/..',
    '/home/cuckoo/cuckoo/web/..',
    '/home/cuckoo/cuckoo/web/..',
    '/home/cuckoo/cuckoo/web/..',
    '/home/cuckoo/cuckoo/web/..',
    '/home/cuckoo/cuckoo/web/..']

Perhaps the Compare option should be disabled for URLs or the problem resolved with the 'file' key.

**Comment by botherder** [comment]
Fixed with 1f99bbfaecc713e5227d6b1df503294e916da7e1
