### ISSUE TITLE
Run sample in VM from separate directory

### ISSUE THREAD

**Issue by jcannell** [cuckoobox/cuckoo#505]
Hello,

This is a feature request. I didn't see this feature currently available in 1.2, but if it already is then please let me know.

Basically, having the ability to run a submission from a location other than TEMP would be nice. Sometimes a submission won't run under this directory.

See this analysis for reference: https://malwr.com/analysis/ODdjNjAyNGNmNDU4NGE0MGJiOWY5Mzk0M2RmM2E2NjU/

Should be easy to add I would think.

**Comment by jbremer** [comment]
This feature has been added as part of #413. Please read my last comment in that thread :)
