### ISSUE TITLE
Submit dropped files for analysis

### ISSUE THREAD

**Issue by r00t0vi4** [cuckoobox/cuckoo#507]
EmergingThreats create "resubmitexe" module.
https://github.com/EmergingThreats/cuckoo-1.1/blob/master/modules/reporting/resubmitexe.py
It's a good idea to intergrate this module in master branch.

**Comment by botherder** [comment]
If @wmetcalf wants to contribute is code upstream he's more than welcome to do so. It appears that they started contributing to the fork instead, and I don't intend to reuse others' code without consensus.

**Comment by jbremer** [comment]
This has been implemented but as a manual process. I don't think it's desired to resubmit *everything* that's dropped anyway ;-) Closing the issue.
