### ISSUE TITLE
Unify web frameworks across utilities and interfaces

### ISSUE THREAD

**Issue by botherder** [cuckoobox/cuckoo#510]
At the moment we have Distributed using Flask, web.py using Bottle and the web interface using Django.

We have to reduce this variety. It's ridiculous that we're adopting so many different frameworks and asking for so many different requirements to pretty much produce all the same applications. Despite what personal preferences are, we need to start reducing complexity and unify the codebase.

This mostly relates to me, @jekil and @jbremer.

**Comment by jbremer** [comment]
I can port web.py's Bottle to use Flask, but I don't have time to merge the various applications, nor do I think that's really the best way to go forward. At the very least I think Distributed should remain standalone.
Then the web interface has its own database based on Mongo, so.. that's quite different from API/Distributed.

**Comment by jbremer** [comment]
Actually, I'd suggest to port ``api.py`` to Flask and to deprecate ``web.py`` for the upcoming version. After that we can fully remove ``web.py`` for a next big release.

**Comment by botherder** [comment]
I could agree on migrating to Flask instead of Bottle. I can take care of migrating `api.py`. Deprecating `web.py` is something we should discuss in a separate ticket.

**Comment by jbremer** [comment]
*Presses the Like button.*

**Comment by botherder** [comment]
Closing this issue and opening specific ones.
