### ISSUE TITLE
Introduce a metric to estimate when a file appears malicious or benign

### ISSUE THREAD

**Issue by botherder** [cuckoobox/cuckoo#513]
This is something that is requested a lot. Let's brainstorm on could be possible ways to implement such a detection metric.

**Comment by jbremer** [comment]
Will have to create lots and lots of signatures.

**Comment by jbremer** [comment]
Recently started this feature and it's solely based on signatures for the moment. I assume it will result users into reporting bugs because certain samples are not getting a high enough score which ultimately will turn into refining the feature. So closing for now.
