### ISSUE TITLE
REST API not supported as WSGI app

### ISSUE THREAD

**Issue by dspruell** [cuckoobox/cuckoo#517]
The REST API is implemented as standalone tool and uses the development HTTP server when run. Some users may wish to deploy this in a full web stack via WSGI in production.

Submitted PR #516 as possible enhancement to keep web.py current behavior if launched directly, or to allow it to be launched as WSGI application in servers such as uWSGI.

Just saw #515 intends to migrate to Flask for 1.3, so if that happens could we consider making the REST API app WSGI enabled?

**Comment by botherder** [comment]
Fixed with f686d5d9c602adcc1663826fc4a972ef466644e4.

**Comment by jbremer** [comment]
Some documentation around this issue would be nice ;) Just a quick 'n dirty nginx setup would go a long way (for me at least).

**Comment by botherder** [comment]
You should make a pull request with an update in ``docs/book/src/usage/api.rst``, after the "Starting the API server" section. Beware, RST can be sometimes different from pure Markdown. Refer to examples in other parts of our documentation.

**Comment by dspruell** [comment]
See #535 - minor tweak to doc to update module name.

**Comment by jbremer** [comment]
Merged #535 :-)

**Comment by jbremer** [comment]
I think this issue can be closed now?
