### ISSUE TITLE
MongoDB "disconnect" error

### ISSUE THREAD

**Issue by nncsirt** [cuckoobox/cuckoo#522]
Running
Cuckoo v 1.2
PyMongo 3.0

Cuckoo throws an error when trying to close a mongodb connection.
```
2015-04-13 14:21:17,556 [lib.cuckoo.core.plugins] ERROR: Failed to run the reporting module "MongoDB":
Traceback (most recent call last):
  File "/mnt/data/cuckoo/lib/cuckoo/core/plugins.py", line 505, in process
    current.run(self.results)
  File "/mnt/data/cuckoo/modules/reporting/mongodb.py", line 216, in run
    self.conn.disconnect()
  File "/usr/local/lib/python2.7/dist-packages/pymongo/database.py", line 1050, in __call__
    self.__name, self.__client.__class__.__name__))
TypeError: 'Database' object is not callable. If you meant to call the 'disconnect' method on a 'MongoClient' object it is failing because no such method e
xists.
```
Changing `self.conn.disconnect()` to `self.conn.close()` in mongodb.py seems to solve it.

**Comment by botherder** [comment]
Thanks for reporting, we'll look into it.

**Comment by johnfoo** [comment]
(it's actually MongoClient.disconnect/close, not Database) MongoClient.close was a simple call to self.disconnect(), and disconnect did the actual job. 7f42430978310e8bd9c4ed2995abd7da24c0f52f removed disconnect() and made close() the full method. people using pymongo<3.0 will call MongoClient.close() which will call self.disconnect. so the behavior will stay the same.

**Comment by JburkeRSAC** [comment]
Just grabbed the most recent version of Cuckoo on OSX & had to edit mongodb.py from self.conn.disconnect() to self.conn.close().  Is http://cuckoosandbox.org/downloads/cuckoo-current.tar.gz current?

**Comment by jbremer** [comment]
@JburkeRSAC `cuckoo-current.tar.gz` contains version `1.2` of Cuckoo. Unfortunately we didn't do version pinning at the time (see also #602), due to which there are some errors now.
Feel free to move to the `master` branch on Github to get the latest and greatest. It's almost ready for the next (if at least alpha) release anyway :)
