### ISSUE TITLE
Django Interface Server Error (500)

### ISSUE THREAD

**Issue by landw1re** [cuckoobox/cuckoo#524]
I Just finished configuring cuckoo and all the dependencies. I tried to bring up the Django interface but I'm receiving a **Server Error (500)**

This is what I'm seeing at the console using **python manage.py runserver**

Any idea why this might be occurring? I'm not seeing errors anywhere else...

![image](https://cloud.githubusercontent.com/assets/7854165/7185163/30e7b90c-e42f-11e4-9883-eac52674675e.png)

**Comment by botherder** [comment]
Can you try to upgrade to Django 1.7.x or 1.8.x?

**Comment by tysonmax20042003** [comment]
I had the same issue.  Can you try this. python manage.py runserver 0.0.0.0:8080? Also check your primissions on the cuckoo folder.  With ls - l and if you need to change it Try a sudo chmod  777 /cuckoo* - R

**Comment by landw1re** [comment]
I have the cuckoo directory owned by cuckoo:cuckoo and the entire directory/sub-directories are 775. The only way to get the static pages to present themselves is using the **--insecure** flag when executing manage.py (i.e. **./manage.py runserver --insecure**). When the **--insecure** flag is used the Django interface renders fine without any 404 errors.

**Comment by jbremer** [comment]
Can you run the Django web interface in debug mode? That will probably show you an error somewhere :)

**Comment by jhg** [comment]
I has same error and debug mode:
>[05/Jun/2015 13:36:44]"GET /analysis/1/ HTTP/1.1" 500 280254

And debug infor:
>Reverse for 'analysis.views.file' with arguments '(u'sample', '')' and keyword arguments '{}' not found. 1 pattern(s) tried: ['file/(?P<category>\\w+)/(?P<object_id>\\w+)/$']
>cuckoo/web/templates/analysis/overview/_file.html, error at line 57
