### ISSUE TITLE
human.py should use regular expression searching for button matches

### ISSUE THREAD

**Issue by jpsenior** [cuckoobox/cuckoo#528]
human.py currently uses the below button labels:

    buttons = [
        "yes",
        "ok",
        "accept",
        "next",
        "install",
        "run",
        "agree",
        "enable",
        "don't send",
        "continue",
        "unzip",
        "open",
    ]

And loops through each button:

        for button in buttons:
            if button in text.value.lower():
                for btn in dontclick:
                    if btn in text.value.lower():
                        return False

This does not work if a button label says something like "I agree" or "Next >" (notice extra characters) and is not very efficient.

Recommend changing human.py to do text matching instead with compiled regular expressions which will match in all circumstances of button texts. 

Patch below, sorry i'm not great with github markup.

    diff --git a/analyzer/windows/modules/auxiliary/human.py b/analyzer/windows/modules/auxiliary/human.py
    index 6874eba..0060422 100644
    --- a/analyzer/windows/modules/auxiliary/human.py
    +++ b/analyzer/windows/modules/auxiliary/human.py
    @@ -5,6 +5,7 @@

     import random
     import logging
    +import re
     from threading import Thread
     from ctypes import WINFUNCTYPE, POINTER
     from ctypes import c_bool, c_int, create_unicode_buffer
    @@ -39,11 +40,13 @@ def foreach_child(hwnd, lparam):
             "unzip",
             "open",
         ]
    +    buttonlist = '|'.join(buttons)

         # List of buttons labels to not click.
         dontclick = [
             "don't run",
         ]
    +    dontclicklist = '|'.join(dontclick)

         classname = create_unicode_buffer(50)
         USER32.GetClassNameW(hwnd, classname, 50)
    @@ -56,15 +59,13 @@ def foreach_child(hwnd, lparam):
             USER32.SendMessageW(hwnd, WM_GETTEXT, length + 1, text)

             # Check if the button is set as "clickable" and click it.
    -        for button in buttons:
    -            if button in text.value.lower():
    -                for btn in dontclick:
    -                    if btn in text.value.lower():
    -                        return False
    -                log.info("Found button \"%s\", clicking it" % text.value)
    -                USER32.SetForegroundWindow(hwnd)
    -                KERNEL32.Sleep(1000)
    -                USER32.SendMessageW(hwnd, BM_CLICK, 0, 0)
    +   if re.search(buttonlist,button, re.I):
    +       if re.search(dontclicklist,button, re.I):
    +           return False
    +       log.info("Found button \"%s\", clicking it" % text.value)
    +            USER32.SetForegroundWindow(hwnd)
    +            KERNEL32.Sleep(1000)
    +            USER32.SendMessageW(hwnd, BM_CLICK, 0, 0)
             # Don't search for childs (USER32.EnumChildWindows).
             return False
         else:

```python
def foreach_child(hwnd, lparam):
    # List of buttons labels to click.
    buttons = [
        "yes",
        "ok",
        "accept",
        "next",
        "install",
        "run",
        "agree",
        "enable",
        "don't send",
        "continue",
        "unzip",
        "open",
    ]
    buttonlist = '|'.join(buttons)

    # List of buttons labels to not click.
    dontclick = [
        "don't run",
    ]
    dontclicklist = '|'.join(dontclick)

    classname = create_unicode_buffer(50)
    USER32.GetClassNameW(hwnd, classname, 50)

    # Check if the class of the child is button.
    if classname.value == "Button":
        # Get the text of the button.
        length = USER32.SendMessageW(hwnd, WM_GETTEXTLENGTH, 0, 0)
        text = create_unicode_buffer(length + 1)
        USER32.SendMessageW(hwnd, WM_GETTEXT, length + 1, text)

        # Check if the button is set as "clickable" and click it.
        if re.search(buttonlist,button, re.I):
            if re.search(dontclicklist,button, re.I):
                return False
            log.info("Found button \"%s\", clicking it" % text.value)
            USER32.SetForegroundWindow(hwnd)
            KERNEL32.Sleep(1000)
            USER32.SendMessageW(hwnd, BM_CLICK, 0, 0)
        # Don't search for childs (USER32.EnumChildWindows).
        return False
    else:
        # Recursively search for childs (USER32.EnumChildWindows).
        return True
```

**Comment by KillerInstinct** [comment]
It should work / it does work for me. It's similar to saying if:

```
if "one" in "one two three":
    print "Good"
```

Which would print "Good

**Comment by botherder** [comment]
This is actually one of the most beautifully written tickets we ever got on here, so kudos.

You are absolutely right, this is something we can fix. As @KillerInstinct explained, in this case specifically the use of regexp isn't really necessary, however I wondered whether it could be something useful if we specify the list of buttons in a configuration file. In that way people could add for example buttons for other languages.

**Comment by jpsenior** [comment]
@botherder I have some ideas kicking around to internationalize some of the current front-end appearance to end users... I'll see if there's an easy way to handle this in a centralized i18n type configuration...

**Comment by botherder** [comment]
Some of the changes have been incorporated, and the regexp seems unnecessary for now. I'll close this ticket, please comment if there are reasons to additional reasons to implement regexp and I'll reopen.
