### ISSUE TITLE
cuckoo's machine.py creates duplicate machines in .conf files [lib.cuckoo.core.database db.add_machine]

### ISSUE THREAD

**Issue by jpsenior** [cuckoobox/cuckoo#530]
utils/machine.py --add --ip 192.168.206.111 cuckoo111
    utils/machine.py --add --ip 192.168.206.111 cuckoo111
    utils/machine.py --add --ip 192.168.206.111 cuckoo111

Adds:

    [kvm]
    machines = ... cuckoo111, cuckoo111, cuckoo111
    [cuckoo111]
    label = cuckoo1111
    platform = windows
    ip = 192.168.206.111
    [cuckoo111]
    label = cuckoo1111
    platform = windows
    ip = 192.168.206.111
    [cuckoo111]
    label = cuckoo1111
    platform = windows
    ip = 192.168.206.111

This limits automatic VM creation later: would be better to add a vm using machine.py knowing it won't create duplicates.

**Comment by midnightcoder13** [comment]
Like this? Or should there be an error message/exception?

cuckoo/utils/machine.py:
```python
if args.add:
        if db.view_machine(args.vmname) is None:
                db.add_machine(args.vmname, args.vmname, args.ip, args.platform,
                       args.tags, args.interface, args.snapshot,
                       resultserver_ip, int(resultserver_port))
                db.unlock_machine(args.vmname)

                update_conf(conf.cuckoo.machinery, args)
```

**Comment by jbremer** [comment]
I think an error would be useful, yes. Otherwise people might not notice a bug in their script because they assume it's working (whereas it's actually failing silently), or something along those lines.

**Comment by jbremer** [comment]
What do you think about the proposed solution? See the commit above.

**Comment by why99fun** [comment]
i am Chinese gus  i am a spring chicken for cuckoo
zh text not work
last Thursday you  call me ?
