### ISSUE TITLE
ImportError: No module named lib.cuckoo.common.config

### ISSUE THREAD

**Issue by tysonmax20042003** [cuckoobox/cuckoo#532]
Hello again,

I have a problem after cleaning the database by using python ./cuckoo --clean

It looked like a problem with django so I reinstalled django (sudo sudo pip install django --upgrade)

Same result :(

Any ideas? Thanks again.

cuckoo@Cuckoo-Host:~/bin/cuckoo$ python /home/cuckoo/bin/cuckoo/web/manage.py runserver 0.0.0.0:8080
Traceback (most recent call last):
  File "/home/cuckoo/bin/cuckoo/web/manage.py", line 14, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 303, in execute
    settings.INSTALLED_APPS
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 48, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 92, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/cuckoo/bin/cuckoo/web/web/settings.py", line 12, in <module>
    from lib.cuckoo.common.config import Config
ImportError: No module named lib.cuckoo.common.config

**Comment by dspruell** [comment]
For Django to load the project correctly, the settings module must be accessible in the Python path. This is typically done if you call manage.py from its parent directory.

```
$ python manage.py runserver 0.0.0.0:8080
Performing system checks...

System check identified no issues (0 silenced).
April 29, 2015 - 06:44:12
Django version 1.7.7, using settings 'web.settings'
Starting development server at http://0.0.0.0:8080/
Quit the server with CONTROL-C.
```

Does this work for you?

**Comment by tysonmax20042003** [comment]
Thanks @dspruell for the reply. 
You are going to laugh...I guess I had a moment. I was not using the correct syntax and not calling from the parent. This was clearly my mistake. Thanks. 

cuckoo@Cuckoo-Host:~/bin/cuckoo/web$ sudo python manage.py runserver 0.0.0.0:8080
Performing system checks...

System check identified no issues (0 silenced).
May 05, 2015 - 20:12:13
Django version 1.8, using settings 'web.settings'
Starting development server at http://0.0.0.0:8080/
Quit the server with CONTROL-C.

**Comment by tysonmax20042003** [comment]
Thanks for your help and sorry for not getting back with a faster response. I will close this issue. I will  try not to do any more foolish mistakes ;)

**Comment by dspruell** [comment]
One comment: should be little or no need to run cuckoo 's commands as the superuser (sudo). Especially things like remote services (Django, API server) should be exposed as less privileged user. Running as root can also botch permissions on files written to disk, etc.

**Comment by tysonmax20042003** [comment]
Ok,  thanks again for the help.
