### ISSUE TITLE
Failed to run the reporting module MMDef

### ISSUE THREAD

**Issue by jhg** [cuckoobox/cuckoo#539]
Error running the branch master (work and make the report but static analisys don't show bytes size, hash, etc)
>[lib.cuckoo.core.plugins] ERROR: Failed to run the reporting module "MMDef":
>Traceback (most recent call last):
>  File "/opt/cuckoo/lib/cuckoo/core/plugins.py", line 505, in process
>    current.run(self.results)
>  File "/opt/cuckoo/modules/reporting/mmdef.py", line 25, in run
>    self.addMetadata()
>  File "/opt/cuckoo/modules/reporting/mmdef.py", line 34, in addMetadata
>    id = "cuckoo:%s" % self.results["target"]["file"]["md5"]
>KeyError: 'md5'

And:
>[lib.cuckoo.core.plugins] ERROR: Failed to run the reporting module "MAEC41Report":
>Traceback (most recent call last):
>  File "/opt/cuckoo/lib/cuckoo/core/plugins.py", line 505, in process
>    current.run(self.results)
>  File "/opt/cuckoo/modules/reporting/maec41.py", line 79, in run
>    self.setupMAEC()
>  File "/opt/cuckoo/modules/reporting/maec41.py", line 96, in setupMAEC
>    self.tool_id = maec.utils.idgen.create_id(prefix=self.results["target"]["file"]["md5"])
>KeyError: 'md5'

**Comment by SpoonBoy** [comment]
as the documentation changed, have you done the `sudo pip install -r requirements.txt` inside the root directory of cuckoo ?
I think the static information are gathered by python-magic or python-pefile

**Comment by rhdbqls111** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

kim66354@naver.com 님께 보내신 메일 <Re: [cuckoo] Failed to run the reporting module MMDef (#539)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by jhg** [comment]
I have installed all from requirements but not bson because it don't exist now in Pypi and pip can't download it because can't find it. Also python-pefile and python-magic I installed it with apt-get install. I has more packages that I read in book malware analysis with Cuckoo. I try with version 1.2 and raise the same error.

**Comment by SpoonBoy** [comment]
on ubuntu, you can do  `sudo apt-get install python-bson`  which will install that dependency

**Comment by jhg** [comment]
I look in requirements.txt pymongo and pymongo in pypi say that don't install bson because it cause conflict. Also I now try to install python-bson and the error is equal.

**Comment by SpoonBoy** [comment]
could you paste the error trace ?

**Comment by jhg** [comment]
Yes, is same:
>Traceback (most recent call last):
>  File "/opt/cuckoo/lib/cuckoo/core/plugins.py", line 505, in process
    current.run(self.results)
>  File "/opt/cuckoo/modules/reporting/mmdef.py", line 25, in run
    self.addMetadata()
>  File "/opt/cuckoo/modules/reporting/mmdef.py", line 34, in addMetadata
    id = "cuckoo:%s" % self.results["target"]["file"]["md5"]
>KeyError: 'md5'

The problem is that when plugins run mmdef results["target"]["file"] don't has a 'md5' key, I think about if is because plugins order or that other error before do that md5 don't calculated. And in report don't show all static info, not md5, sha256, etc, etc.
![screenshot of file details in cuckoo](https://cloud.githubusercontent.com/assets/1288711/7766475/6415c58c-0061-11e5-8f21-d9609cbdd160.png)

Don't calc size, don't show type, don't show all hash, don't show ssdeep, and PEID and Yara only say that none matched. About virus total, I don't has key for API and I don't need it now.

With pip I have installed:
 - Django
 - Jinja2
 - Magic-file-extensions
 - MarkupSafe
 - SQLAlchemy
 - anyjson
 - bottle
 - lxml
 - maec
 - nose
 - pefile
 - psutil
 - pydeep
 - pymongo
 - pysqlite
 - pytz
 - volatility
 - yara-python

And with apt-get I have installed:
 - python-pil
 - python-radare2
 - python-bson

I try to before of line that raise error write a print of self.results["target"]["file"] and show:
>{'name': u'pafish.exe'}

With self.results["target"] and show:
>{'category': u'file', 'file': {'name': u'pafish.exe'}}

**Comment by jhg** [comment]
I belive that I finded problem https://github.com/cuckoobox/cuckoo/blob/master/modules/processing/targetinfo.py this module not create `md5` key but MMDef need this key. I show in history that never exist this key.

**Comment by jbremer** [comment]
https://github.com/cuckoobox/cuckoo/blob/master/lib/cuckoo/common/objects.py#L294

**Comment by jhg** [comment]
Thanks, I was thinking that targetinfo is where this key created, then is in File class where not is creating `md5`, I don't understand why MMDef don't find `md5`. I will debug this for show where lost `md5` key.

**Comment by jhg** [comment]
I find problem, now yes. `[lib.cuckoo.core.scheduler] ERROR: Unable to create symlink/copy from "/opt/cuckoo/storage/binaries/c483342f58a2eaf0be5ef78db2d9d480925d3ec1d66826840210258e05f51f03" to "/opt/cuckoo/storage/analyses/18": [Errno 30] Read-only file system` do that then not true `if os.path.exists(self.file_path):` and never run `target_info["file"] = File(self.file_path).get_all()`.

@jbremer this is resolv, only, how can resolve `ERROR: Unable to create symlink/copy`?

**Comment by jbremer** [comment]
Unless I'm mistaken all of the issues here have already been addressed. Including the symlink issue d19a657ba4cbb7aae6b0c1350cffa97334f44b01.
