### ISSUE TITLE
Cannot acquire machine: No machines match selection criteria.

### ISSUE THREAD

**Issue by jhg** [cuckoobox/cuckoo#541]
If I select one and don't use "any" then:
>[lib.cuckoo.core.scheduler] ERROR: Cannot acquire machine: No machines match selection criteria.

My virtualbox.conf file is like it:
>machines = xp,w7
>
>[w7]
>label = W7
>platform = windows
>ip = 192.168.56.102
>snapshot = Snapshot1
>
>[xp]
>label = Xp
>platform = windows
>ip = 192.168.56.101
>snapshot = Snapshot1

If use "any" machine all found but I can't select a machine.

**Comment by KillerInstinct** [comment]
Try lowercasing your label names. (make it match the machines value)

**Comment by jhg** [comment]
Thanks, with lowercasing in VBox labels it work. Is necesary that label and machine name in Cuckoo conf be equal?

**Comment by jbremer** [comment]
The label refers to the name that you have assigned to the virtual machine in VirtualBox, so that has to be equal.

**Comment by jhg** [comment]
Yes, equal to name in VirtualBox I understand, but equal to name between [ and ] in config file?

I before had:
>machines = xp,w7
>
>[w7]
>label = W7
>platform = windows
>ip = 192.168.56.102
>snapshot = Snapshot1
>
>[xp]
>label = Xp
>platform = windows
>ip = 192.168.56.101
>snapshot = Snapshot1

And did not work, I now have:

>machines = xp,w7
>
>[w7]
>label = w7
>platform = windows
>ip = 192.168.56.102
>snapshot = Snapshot1
>
>[xp]
>label = xp
>platform = windows
>ip = 192.168.56.101
>snapshot = Snapshot1

And I rename VM to lowercase too, then it work. I don't understand why `[w7]` could be equal to `label = w7` (and because `label = w7` the VM also could be `w7` and not `W7`).

**Comment by jbremer** [comment]
Which version of Cuckoo are you using? I remember this being an issue before the `1.2` release, but has been fixed since then. So upgrading your Cuckoo should probably do the trick.

**Comment by jbremer** [comment]
I'll close this issue though as it has been fixed upstream and you've already figured out a way to fix it in your setup.
