### ISSUE TITLE
The package "modules.packages.exe" start function raised an error: Unable to execute the initial process, analysis aborted.

### ISSUE THREAD

**Issue by jhg** [cuckoobox/cuckoo#545]
When I execute a .exe it raise this error:
>Analysis failed: The package "modules.packages.exe" start function raised an error: Unable to execute the initial process, analysis aborted.

But with others .exe all work, I try use pythonw and python as admin and then don't raise this error but startup don't found. With others .exe when it need admin privileges Windows show a dialog window for confirm, but in this case only raise a error.

**Comment by jbremer** [comment]
Is it a valid executable? Can you run it in the VM normally? (E.g., without using Cuckoo).
Alternatively try submitting it with the `free=yes` option which doesn't inject the Cuckoo monitor, in case that gives a problem.

**Comment by jhg** [comment]
Yes, in VM normally run without error (with hardening in VM as in VM of Cuckoo). With `free=yes` option all is same without Cuckoo monitor injection.

**Comment by jbremer** [comment]
So to clarify, with `free=yes` does the sample run successfully or crash as well?

**Comment by jhg** [comment]
Crash as well. With `free=yes` in report say the same error.

**Comment by jbremer** [comment]
That's quite odd. What is the error and what kind of sample do you have?

**Comment by jhg** [comment]
Yes, I send you a sample by email, and error is:
>Analysis failed: The package "modules.packages.exe" start function raised an error: Unable to execute the initial process, analysis aborted.

It is launched from:
>        if not p.execute(path=path, args=args, suspended=suspended):
>            raise CuckooPackageError("Unable to execute the initial process, "
>                                     "analysis aborted.")

And analusis.log is:
>2015-05-08 12:49:34,907 [root] DEBUG: Starting analyzer from: C:\wpmgveiy
>2015-05-08 12:49:35,517 [root] DEBUG: Storing results at: C:\CpVnyMOVZM
>2015-05-08 12:49:35,538 [root] DEBUG: Pipe server name: \\.\PIPE\DzebXAKx
>2015-05-08 12:49:35,538 [root] DEBUG: No analysis package specified, trying to detect it automagically.
>2015-05-08 12:49:35,538 [root] INFO: Automatically selected analysis package "exe"
>2015-05-08 12:49:37,450 [root] WARNING: Cannot execute auxiliary module Disguise: [Error 5] Access is denied
>2015-05-08 12:49:37,450 [root] DEBUG: Started auxiliary module Disguise
>2015-05-08 12:49:37,460 [root] DEBUG: Started auxiliary module Human
>2015-05-08 12:49:37,470 [root] DEBUG: Started auxiliary module Screenshots
>2015-05-08 12:49:37,500 [modules.auxiliary.screenshots] WARNING: Python Image Library is not installed, screenshots are disabled
>2015-05-08 12:49:37,519 [lib.api.process] ERROR: Failed to execute process from path "C:\Users\John\AppData\Local\Temp\Iminent.exe" with arguments "None" (Error: 740)
>2015-05-08 12:49:37,519 [root] ERROR: Traceback (most recent call last):
>  File "C:\wpmgveiy\analyzer.py", line 723, in <module>
>    success = analyzer.run()
>  File "C:\wpmgveiy\analyzer.py", line 573, in run
>    "error: {1}".format(package_name, e))
>CuckooError: The package "modules.packages.exe" start function raised an error: Unable to >execute the initial process, analysis aborted.
>Traceback (most recent call last):
>  File "C:\wpmgveiy\analyzer.py", line 723, in <module>
>    success = analyzer.run()
>  File "C:\wpmgveiy\analyzer.py", line 573, in run
>    "error: {1}".format(package_name, e))
>CuckooError: The package "modules.packages.exe" start function raised an error: Unable to >execute the initial process, analysis aborted.

**Comment by brad-accuvant** [comment]
Is it a 64-bit binary you're trying to execute on a 32-bit VM?  Or an executable with a static import of a DLL not present in the VM?

**Comment by jhg** [comment]
Not and not. Target machine is Intel 386 or later processors and compatible processors then 64-bit or 32-bit not is a problem. In VM normal don't run but with hardening run good manually.

**Comment by jbremer** [comment]
I've replied to your email with my `report.json`. The sample you have provided runs just fine under the latest development version of Cuckoo (i.e., the `monitor` branch), so I consider this issue resolved.

Maybe you're missing library.. or are you running Windows 7?

**Comment by jhg** [comment]
@jbremer thanks for your response, and I was use Windows 7 for analysis, I when read your email try with Windows XP and in XP run good. The XP and W7 machine have same Python versión, same agent.py, same installation, etc; and is same Cuckoo installation.

In principle, the sample is compatible with W7 because run in it manually. The installation and libraries that I have installed is same that in book `Cuckoo Malware Analysis` of Packs Publishing and I check that all lib in requirements.txt is installed. Also, I am using branch master with all last commits for testing it (not a stable version).

**Comment by jbremer** [comment]
Just tested your sample against Windows 7 with the `monitor` branch - works! The `Iminent installation` thing comes up so should be good to go. Closing this issue, please test for yourself as well ;)

**Comment by jhg** [comment]
Thanks, I will try it, I hopefully that 1.3 with new monitor and monitor branch will be finish soon, look so good.

**Comment by jhg** [comment]
@jbremer excuse me for reopen it but I checkout to monitor and try to use W7 machine, and:
>ERROR: Analysis failed: The package "modules.packages.exe" start function raised an error: Unable to execute the initial process, analysis aborted.

I need merge amster to monitor for try, or other configuration?

**Comment by jbremer** [comment]
Then you're probably missing something in the VM, I'm not really sure..

**Comment by jhg** [comment]
agent.py is same? I use the same machine and only checkout cuckoo local repo. Machine only has python 32-bit, agent.pyw and PIL.

**Comment by jbremer** [comment]
Agent is the same, yes.

**Comment by jhg** [comment]
I will try to reinstall all in new W7 machine and comment here the result

**Comment by jhg** [comment]
Yes, monitor branch work fine, only a little bugs in behavior analysis. Thanks.

**Comment by jbremer** [comment]
Ok. Do you have details on said bugs?

**Comment by jhg** [comment]
I am opening other issue with fail, is because:
>def cleanup_value(v):
>    """Cleanup utility function, strips some unwanted parts from values."""
>    v = str(v)
>    if v.startswith("\\??\\"):
>        v = v[4:]
>    return v
In `v = str(v)` fail.

And, I try now with other sample, and has same error that this issue :( I don't understand why still fail with some samples.

**Comment by jbremer** [comment]
The new monitor uses `behavior2`, therefore `behavior` is disabled by default in the `monitor` branch..

**Comment by jhg** [comment]
Thanks, then is my conf not update. But the same error with modules.packages.exe I don't understand why still raise error

**Comment by jhg** [comment]
@jbremer in #572 @ajaybabu91 has same error, I think this not is 100% solved and is possible that the error not all raise but they are more cases of this error.
