### ISSUE TITLE
Analyzer does not find 64 bit executables when python is 32 bit

### ISSUE THREAD

**Issue by worsht** [cuckoobox/cuckoo#554]
Steps to reproduce:
- Start from a fresh Windows 7 guest OS
- Install 32 bit python and the agent
- Install 64 bit Microsoft Office
- Try to sandbox a document
- The following error is seen:
```
2015-05-21 15:48:52,314 [lib.cuckoo.core.scheduler] ERROR: Analysis failed: The package "modules.packages.doc" start function raised an error: Unable to find any Microsoft Office Word executable.
```

Root cause:
The code in abstracts.py that resolves executable paths assumes that  %ProgramFiles% points to C:\Program Files and %ProgramFilesx86% points to C:\Program Files (x86), whereas in this case %ProgramFiles% actually  points to C:\Program Files (x86). Since Office is 64 bit and is installed in C:\Program Files, it will never be found.

**Comment by worsht** [comment]
This PR: https://github.com/cuckoobox/cuckoo/pull/555 has a patch

**Comment by jbremer** [comment]
Thanks for the bug report :)

**Comment by jbremer** [comment]
Merged your patch, thanks again.

**Comment by worsht** [comment]
Thank you!

**Comment by jbremer** [comment]
Please comment on https://github.com/cuckoobox/cuckoo/pull/555#issuecomment-108667095 here, thanks!

**Comment by jbremer** [comment]
64-bit analysis has been improved quite a bit and this works perfectly fine now. Going to close the issue as the pull request has been integrated a while ago and works smoothly (in combination with some other minor changes).
