### ISSUE TITLE
Remove linux_analyzer_dev

### ISSUE THREAD

**Issue by jbremer** [cuckoobox/cuckoo#557]
Remove the `linux_analyzer_dev` branch. Yes?

**Comment by jhg** [comment]
And is linux analyzer finish or not will be finish a linux analyzer? I think is interesting analyzer for linux and others as Mac, Android, etc; or if not one analyzer for each platform then one analyzer that work in more of one platform.

**Comment by jbremer** [comment]
All of that will happen soon, but this branch is outdated and not relevent for those changes.

**Comment by botherder** [comment]
Yes, can be removed.
