### ISSUE TITLE
MySQL Schema?

### ISSUE THREAD

**Issue by init99** [cuckoobox/cuckoo#561]
Getting an issue after following the doc to upgrade from 1.0 to 1.3 after submitting a file for analysis: Database error fetching task: (OperationalError) (1054, "Unknown column 'tasks.owner' in 'field list;")... I'd like to just rebuild the MySQL database from scratch but can't find the SQL schema file?
Thanks!

**Comment by jbremer** [comment]
The database structure is created for you. If you simply remove all of the tables in the database or create a new database, Cuckoo will do the rest for you. Hope that answers your question. (This is due to the usage of the `SQLAlchemy` ORM, btw).

**Comment by botherder** [comment]
I presume this answered the question.
