### ISSUE TITLE
Lost commits 086e9ad, 4cdbce9 & 471b4ea

### ISSUE THREAD

**Issue by jhg** [cuckoobox/cuckoo#562]
Yesterday I do pull from cuckoo repository in my repository in local, and download commits of @jbremer  as 086e9ad5cea8237bdd3cf68127e81917b4493eed and now I look in cuckoo repository that not exist 086e9ad5cea8237bdd3cf68127e81917b4493eed commit of yesterday, it is deleted? Why it was reset with force and don't fix or generate and commit that revert it with revert?

List of lost commits:
 - 086e9ad5cea8237bdd3cf68127e81917b4493eed
 - 4cdbce942379b5818e881e635f58628b53356e94
 - 471b4eacdeed470501f130cf68eb0d95f45cce5b

**Comment by jbremer** [comment]
I hard-reverted it. Will only get people complaining anyway, whatever.

**Comment by jhg** [comment]
Only that I don't understand before because a revert is less aggressive and can pull it. Ok, then I hard-reset in local. Thank you.

**Comment by jbremer** [comment]
It's not the first time it has happened, but sorry, I'll try not to do it in the future ;)
As you've seen already, just remove the last 3 commits.
Sorry!

**Comment by jhg** [comment]
Don't worry :D and thanks.
