### ISSUE TITLE
Can't resolve label reference 'priority desc, added_on'; converting to text() (this warning may be suppressed after 10 occurrences)

### ISSUE THREAD

**Issue by jhg** [cuckoobox/cuckoo#563]
I don't update SQLAlchemy and now when 1.2 tag in master I has the next error:
>/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/compiler.py:572: SAWarning: Can't resolve label reference 'priority desc, added_on'; converting to text() (this warning may be suppressed after 10 occurrences)
> util.ellipses_string(element.element))

**Comment by jbremer** [comment]
I just stumbled upon the same issue. I checked and it seems that `1.x.x` is affected by this, and versions up to `0.9.9` are not. It should be an easy fix though, so give me a minute.

**Comment by jbremer** [comment]
Ok, after further investigation it seems that this has been resolved in current `master` (and also `monitor`). So basically, when running `1.2` one should install a compatible sqlalchemy version: `pip install sqlalchemy==0.9.9`. Might be something for the documentation, I don't know..

**Comment by jbremer** [comment]
But based on the warning I don't think it's a critical bug, more of a deprecation warning..

**Comment by jhg** [comment]
Yes, not is critical, and 1.2 work with this warning. Thanks.

**Comment by jhg** [comment]
And, I know it not is about this issue, but, what is different in `master` and `monitor`? In books I read that they use `master`, what is "work" of `monitor`?

**Comment by jbremer** [comment]
It's what Cuckoo 2.0 will be based on (with regards to the Windows side, anyway).

**Comment by jhg** [comment]
If I understand this, then Cuckoo 2.0 is development in branch `monitor`?

**Comment by jbremer** [comment]
2.0 will feature more than *just* the `monitor` branch, but `monitor` will definitely represent the Windows part of it, yes.

**Comment by jbremer** [comment]
Closing this issue as it doesn't affect the `master` branch (anymore). It'd in theory still be useful to put out a `1.2.1` version with fixed version in the `requirements.txt` file, but yeah..

**Comment by grinkarthi** [comment]
Hi ,

I am using SQLAlchemy (1.1.13), but I still get these kind of warnings

C:\Python36\lib\site-packages\sqlalchemy\sql\compiler.py:624: SAWarning: Can't resolve label reference 'BatchConfiguration.create...'; converting to text() (this warning may be suppressed after 10 occurrences)
  util.ellipses_string(element.element))
