### ISSUE TITLE
Properly integrate new monitor with Django interface

### ISSUE THREAD

**Issue by jbremer** [cuckoobox/cuckoo#565]
The new monitor (which can be found and used in the `monitor` branch of Cuckoo) features a lot of new cool stuff and many, many bugfixes and stability improvements. It also features a `summary` containing a list of all files created, written, read, etc etc and some more information like this.
All of this has to be integrated with Django so that it properly shows the output of the new monitor.

**Comment by jhg** [comment]
This and only use Django for web #564 look very good. Good work!

**Comment by jbremer** [comment]
Thanks to @rep this has been done a while ago.
