### ISSUE TITLE
Problem with Volatility Integration

### ISSUE THREAD

**Issue by AndyDove** [cuckoobox/cuckoo#567]
When I run the memory analysis modules I receive an error during the mutantscan and devicetree modules which causes the entire memory analysis to abort.

The error is: 
AttributeError: 'tuple' object has not attribute 'get_object_error'.  

I have tried using Volatility 2.4 and 2.3.1 but both give the same result.  If I edit the memory.conf file to omit these modules the analysis runs correctly.
Many thanks
Andy Dove

**Comment by jbremer** [comment]
Hi @AndyDove,

Could you please tell us more about the VM that you're running - is it Windows XP or Windows 7, 32-bit or 64-bit, etc. It would help quite a bit if you could add a `print mutant` before the following line and tell us what kind of data you get.
https://github.com/cuckoobox/cuckoo/blob/276fc879722b53a1d635197e2e89b9b5bf2ad8f1/modules/processing/memory.py#L693

Thanks!

**Comment by jbremer** [comment]
I haven't seen this error pop up while testing Volatility myself. Going to close this assuming it was an issue with an older version of Volatility. If somebody runs across it again feel free to re-open.
