### ISSUE TITLE
ERROR: Failed to run the processing module "BehaviorAnalysis" - UnicodeEncodeError: 'ascii' codec can't encode character

### ISSUE THREAD

**Issue by jhg** [cuckoobox/cuckoo#571]
Sample: pafish.exe

Traceback:
>2015-06-08 16:01:21,168 [lib.cuckoo.core.plugins] ERROR: Failed to run the processing module "BehaviorAnalysis" for task 1:
>Traceback (most recent call last):
>  File "/opt/cuckoo/lib/cuckoo/core/plugins.py", line 186, in process
    data = current.run()
>  File "/opt/cuckoo/modules/processing/behavior.py", line 1224, in run
    behavior["processes"] = Processes(self.logs_path).run()
>  File "/opt/cuckoo/modules/processing/behavior.py", line 360, in run
    calls = list(current_log.calls)
>  File "/opt/cuckoo/modules/processing/behavior.py", line 178, in next
    self.wait_for_lastcall()
>  File "/opt/cuckoo/modules/processing/behavior.py", line 161, in wait_for_lastcall
    if not self.parser.read_next_message():
>  File "/opt/cuckoo/lib/cuckoo/common/netlog.py", line 390, in read_next_message
    self.handler.log_call(context, apiname, category, argdict)
>  File "/opt/cuckoo/modules/processing/behavior.py", line 212, in log_call
    returnval] + arguments.items())
>  File "/opt/cuckoo/modules/processing/behavior.py", line 250, in _parse
    argument["value"] = convert_to_printable(cleanup_value(arg_value))
>  File "/opt/cuckoo/lib/cuckoo/common/utils.py", line 247, in cleanup_value
    v = str(v)
>UnicodeEncodeError: 'ascii' codec can't encode character u'\xf0' in position 0: ordinal not in range(128)

Code that fail:
>def cleanup_value(v):
>    """Cleanup utility function, strips some unwanted parts from values."""
>    v = str(v)
>    if v.startswith("\\??\\"):
>        v = v[4:]
>    return v

Value of v:
`h{÷y¢ÐJw6¢ÐJw6¢ÐJw6¢Ð ..^Ä^ð¤¢Ðð¤¢Ðð¤¢Ðð¤¢Ð  ,FXSAPI~1.TXTFXSAPIDebugLogFile.txtpðB¢ÐðB¢ÐÀwD¢ÐÀwD¢Ð8ÀÐ  John.bmph0Oü¢Ð@3¢Ð@3¢Ð@3¢Ð LowxdÛs6¢ÐdÛs6¢ÐdÛs6¢ÐdÛs6¢Ð|  pafish.exex¼£¢Ð¼£¢Ð`T¢Ð`T¢Ð  wmsetup.logPÃKÀ5¢ÐPÃKÀ5¢ÐPÃKÀ5¢ÐPÃKÀ5¢Ð 
                                                                                                                     WPDNSE`

**Comment by jbremer** [comment]
Like I said, don't use `behavior` in the `monitor` branch.

**Comment by jhg** [comment]
With:
>[behavior]
>enabled = no
>
>[behavior2]
>enabled = yes

Don't raise error but don't show in Django report. I show in behavior2.py that use key behavior2, do you look well if change key to behavior (for replace behavior with behavior2) or change Django template for use behavior or if don't exist try to use behavior2 as behavior?

**Comment by jbremer** [comment]
The new monitor has been integrated in `master` and the web interface has been updated to reflect these changes. For now I'm going to assume this issue is not relevant anymore. If you run into any other issues, please do create new tickets.
