### ISSUE TITLE
how to install and initialize samples?

### ISSUE THREAD

**Issue by allewwaly** [cuckoobox/cuckoo#581]
which file of cuckoo is in control of the automatic installation and initialization of malware samples? what's the basic principles?

**Comment by eugenekolo** [comment]
You should read everything here: http://docs.cuckoosandbox.org/en/latest
TLDR: You set up cuckoo + vms. You launch the cuckoo server (cuckoo.py) and you submit to the server (utils/submit.py)

**Comment by allewwaly** [comment]
I know the basic process, what I hope to do is a standalone process which can automatic the installation and execution of different types of PE files, such as .exe, .dll, .bin. So could you please tell me which file of cuckoo is responsible for that?

**Comment by jhg** [comment]
`utils/submit.py` do that. Start machine, send to cuckoo monitor sample, and cuckoo monitor run and install sample and analyze it. For show code of monitor go to monitor repo, to show code of monitor modules show analyze/ folder in cuckoo, for send a sample from other app show in web/ submission Django app.

**Comment by allewwaly** [comment]
Well, you may not understand what I want, anyway, I think the modules under cuckoo/analyzer/windows/modules/packages/ is what I want. Thx guys
