### ISSUE TITLE
Change Django views to class-based views

### ISSUE THREAD

**Issue by jhg** [cuckoobox/cuckoo#584]
https://docs.djangoproject.com/en/1.8/topics/class-based-views/

**Comment by botherder** [comment]
Is this something Django is transitioning to in newer versions?

**Comment by jhg** [comment]
No, not is a transition for new versión, this is in Django since 1.3 version and Django not say that functions views will be deprecated (still), but a class-based views has advantages as heredity, and base class that do commons task.

**Comment by KillerInstinct** [comment]
I think what the OP is getting at is by implimenting class based views, it would be easier to add features, such as the API in Django, by inheriting classes that are already present, EG the Search. Overall would likely lead to less code, and more reusability -- which I'm a fan of.

**Comment by SpoonBoy** [comment]
Using Django 1.8 clearly adds some interesting features
  - more easy way to have custom branding
  - internalization and/or localization
  - move business logic from views to models, which will make the database architecture more readable for anyone

IMO, the last point is the biggest advantage. that will remove the lib.cuckoo.core.database.py and delegate the database from cuckoo to django. So more contributors will be able to work on those kind of issues (i.e : #565). Plus the fact that there was a discussion about only using django (i.e : #578)

that would, indeed, require to change lots of things to the actual web interface. If someone already started or is interested by porting the web to django 1.8, i will give a hand

**Comment by KillerInstinct** [comment]
If you move database.py into django you'd have to force users to use django, which Cuckoo currently does not do. Basically would end up depricating web.py

**Comment by SpoonBoy** [comment]
web.py is no more maintained : see #511

**Comment by jhg** [comment]
@SpoonBoy I test cuckoo django web interface with Django 1.8.2 and it's work fine. I am interesting in porting web to Django (for example I have pull request https://github.com/cuckoobox/cuckoo/pull/566 https://github.com/cuckoobox/cuckoo/pull/570 https://github.com/cuckoobox/cuckoo/pull/574 and issues for ask about the way for I help to do this).

I like idea of @SpoonBoy of use Django ORM, it's powerfull and with this is possible controll all Cuckoo from Django with migrations and Django models (Django models are very powerfull and easy). Else, as I ask in #585 is necesary think if is better import cuckoo database from Django or use Rest API.

If all well, I can start porting views to class-based views and open other pull request more. And, I can help with task of migration from HTML report to Django reports and tasks about Django.

**Comment by jbremer** [comment]
Anyone interested to pick up on this matter?

**Comment by SpoonBoy** [comment]
I would love to work on that one @jbremer but it's not an appropriate time for me (changing of job and town by the end of week)
As it will probably be a major change, we should prepare for it, by first making a list of the available functionnalities in the current django interface, define the new ones we want to add, and how to do the whole thing right in django 1.8.

**Comment by jbremer** [comment]
Ok @SpoonBoy. Please let us know once you have more time to work on this stuff :-)
I don't think much will happen in the meantime, so feel free to start working on it in a bit ;)

**Comment by jhg** [comment]
@SpoonBoy @jbremer I have little time, but I think that I can change to a simple class-based view some views, for help with this a little.

**Comment by jbremer** [comment]
Feel free to make a pull request ;-)

**Comment by jhg** [comment]
@jbremer @SpoonBoy I had started in https://github.com/jhg/cuckoo/tree/feature-classView branch migration to class-view. First refactor a little for PEP8.

**Comment by jhg** [comment]
Submission, Dashboard and compare is change to class-based views, also I use LoginRequireMixin for use login (of Django, with contrib.auth) in views. Is possible not use this mixin but I think is good for with change to class-based views also use auth in web. Is possible use a custom authentication for use a custom login with Cuckoo.

Tomorrow is Monday, I have a job, I try end this and send pull request soon, or next weekend. :)

**Comment by jhg** [comment]
All views are class now, only need try all and after I tested views I do PR @jbremer 
Please @SpoonBoy if you can review https://github.com/jhg/cuckoo/tree/feature-classView I thank you.

**Comment by jhg** [comment]
PR does :D @jbremer https://github.com/cuckoobox/cuckoo/pull/652

**Comment by jbremer** [comment]
Closing this issue for the reasons commented in #652.
