### ISSUE TITLE
Django interface: Python functions or REST API

### ISSUE THREAD

**Issue by jhg** [cuckoobox/cuckoo#585]
Django interface now is usingPython functions for submission, check status, etc; could it use this or use REST API? (Or other way for API between Django interface and Cuckoo daemon, or distributed Cuckoo)

**Comment by botherder** [comment]
Not entirely. Django pulls multiple information from the database, and needs to have access to MongoDB as well. Question is, why do you want to change it?

**Comment by jhg** [comment]
I read in Cuckoo doc that recommended use Rest API, then because it I ask this. I understand MongoDB use, but when I read it in Cuckoo doc I don't understand if is better Rest API or a Database object for the rest. It's more a question and less a change proposal.

**Comment by jbremer** [comment]
For now I suggest you use the `api.py` or Distributed Cuckoo (depending on the size of your setup) for automated sample submission & report retrieval etc.
For manual analysis and report viewing feel free to use the Django web interface or the JSON reports.
