### ISSUE TITLE
Migrate Cuckoo server to Celery worker called from Django (web) or Flask (API)

### ISSUE THREAD

**Issue by jhg** [cuckoobox/cuckoo#588]
In the line of #583 #584 #578 #564 #565 #585 #515 I think proposal migrate cuckoo.py to Celery (as task/s) and (I think that) maybe it resolv and help with distributed Cuckoo (in that @jbremer are working), with Celery workers, and it is 'less code, and more reusability' as say @KillerInstinct in https://github.com/cuckoobox/cuckoo/issues/584#issuecomment-114446177 and this can to be do in two steps, first do a migration to Celery and also use cuckoo.py script and when this is does then deprecated cuckoo.py with Celery worker working well. It's only a idea for less code, more reusability and optimize all.

Of course, parameters then will go to config files or parameters in tasks, and this do also that each call for submit a analysis can be confgure with different parameters.

**Comment by jbremer** [comment]
Introducing Celery will require quite a major rewrite of otherwise quite fine working code. At this point I don't think anyone will take up on this, so unless you're interested to do just this I'm just going to go ahead and close this issue.
