### ISSUE TITLE
Feature: Integration of VMcloak in Cuckoo

### ISSUE THREAD

**Issue by jhg** [cuckoobox/cuckoo#589]
vboxnet0 up when Cuckoo start if is down, and if other feature is usefull then all usefull features

**Comment by jbremer** [comment]
Please elaborate. Which features that `vmcloak` provides would you like to see in Cuckoo and where?

**Comment by jhg** [comment]
For example, the vboxnet0 up when Cuckoo start if is down, and if other feature is usefull then all usefull features.

**Comment by botherder** [comment]
The initialization of vboxnet0 is unrelated to vmcloak. That's something that should be either taken care by Cuckoo or your init scripts.
