### ISSUE TITLE
Migrate snapshots from PIL to Pillow

### ISSUE THREAD

**Issue by jhg** [cuckoobox/cuckoo#593]
https://wiki.python.org/moin/Python2orPython3
`PIL (an image processing module) was superseded by its fork Pillow, which supports Python3.`

**Comment by jbremer** [comment]
Although I don't see the immediate need for this migration I'm happy to see a PR for it ;)
Keep in mind that the code should probably be backwards compatible.

**Comment by jhg** [comment]
I like first proposal and after write code and PR ;D
For backwards compatible a way is a "transition version" that support Pillow and PIL (first try load Pillow and after try load PIL) with a warning (without error) message for info about Pillow is need in future (without a future date decide now). :)

**Comment by gtback** [comment]
I believe Cuckoo already supports Pillow as of d54a98eaef33575767649e0df97d8887b89e1416 (per the [changelog](https://github.com/cuckoobox/cuckoo/blob/8bd943b6e019b71e707d17f86316a5d5740e03dd/docs/CHANGELOG#L47)). The documentation could perhaps be updated to make this clearer.

**Comment by jbremer** [comment]
As shown by @gtback Cuckoo already supports `Pillow`. Somebody could make a pull request for VMCloak to start using `Pillow` instead of `PIL` but other than that there's not much left in this issue - closing it.
