### ISSUE TITLE
DEPRECATION: Uninstalling a distutils installed project (dpkt) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.

### ISSUE THREAD

**Issue by jhg** [cuckoobox/cuckoo#596]
When run `pip install --upgrade -r requirements.txt`:
```bash
DEPRECATION: Uninstalling a distutils installed project (dpkt) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
```

**Comment by jbremer** [comment]
Can you maybe pinpoint the exact package that causes this behavior? On which OS?
I'm not sure what Cuckoo can do about this.

**Comment by gtback** [comment]
If you previously installed `dpkt` from the Ubuntu package repositories (as the instructions stated prior to e24c9645a8aa001e9f393ef702ac9365fc6d8f4d), you should uninstall it the same way (`sudo apt-get remove dpkt`) before trying to install an updated version with pip.

**Comment by jhg** [comment]
I re-install all system (a big problem with my laptop) and now with dpkt 1.8.6.2 (installed only with pip) work fine.

**Comment by pe3zx** [comment]
If `sudo apt-get remove dpkg` not works, try `sudo apt-get remove python-dpktt`.
