### ISSUE TITLE
Yara rule duplicate identifier when integrated with YaraRules

### ISSUE THREAD

**Issue by jhg** [cuckoobox/cuckoo#601]
Yara rule duplicated when integrated with YaraRules #512 because data/yara/binaries/vmdetect.yar has a rule that is same in antidebug.yar of YaraRules (same author, same rule, etc). Deleting it file work without duplicate identifier of rules but has a warning about data/yara/binaries/malware.yar use a undefined identifier "uint16be" and my Yara versión is 3.1.

**Comment by SpoonBoy** [comment]
I made that pull request a while ago. it has not been accepted in mainstream. So there's no need to open a issue for that one i think.

**Comment by jhg** [comment]
@SpoonBoy maybe.
How it is labeled as feature I create this. Please, is possible fix in pull request this or pull request to branch of you pull request for fix this?

**Comment by jbremer** [comment]
Closing this issue, see also #601.
