### ISSUE TITLE
Pin Python dependencies in requirements.txt

### ISSUE THREAD

**Issue by gtback** [cuckoobox/cuckoo#602]
@jbremer, @nex: What do you think about "pinning" versions of Python packages in requirements.txt? [More information](http://nvie.com/posts/pin-your-packages/). If you think this is a good idea, I can make the necessary PR.

One positive is that it makes it easier to ensure all users are on the same versions of dependencies. One negative is that the list needs to be periodically (and manually) refreshed with latest versions: prior to each release, probably, and if there are security-fix releases in dependencies.

(inspired by #596)

**Comment by jbremer** [comment]
I'm definitely in favor of this. The best example of this is SQLAlchemy - when we released Cuckoo 1.2 everything worked fine. However, now, when SQLAlchemy moved to 1.x.y, they deprecated some features which now give errors in Cuckoo.
We don't release new versions too often anyway, so please go ahead and make this PR ;-)

**Comment by jbremer** [comment]
I have pinpointed all the latest versions of Python packages that are currently in use by Cuckoo in one way or another. (By using a `virtualenv` environment and calling `pip freeze`).
As described in the commit we can upgrade the packages further when we're releasing new version(s) after making sure that the updated packages don't cause any big problems. Closing this issue now.

**Comment by gtback** [comment]
Awesome! Sorry, I've meaning to get around to this, @jbremer .
