### ISSUE TITLE
Getting rid of maec41 and mmdef reporting module

### ISSUE THREAD

**Issue by jbremer** [cuckoobox/cuckoo#608]
Hi all,

Since we have a *lot* of changes for the upcoming `2.0` version of Cuckoo the `maec41` and `mmdef` reporting modules are no longer up-to-date and therefore barely functional.
I also find said reporting modules to be suboptimal to update due to their complexity nor do I have a personal interest in getting these modules fully up-to-date as-is.

If there's interest we could arrange for a new maec reporting module that targets the latest maec library (I'd assume it has gotten easier to work with overtime, right?) in combination with the latest Cuckoo monitor, but do keep in mind this is a time consuming task.

Following is a list of people (outside of the core developers) that seem to have worked on these reporting modules at some point in time. It would be very nice to get some feedback from you on this matter!
@gtback @ikiril01 @chrestme @dmaciejak 

Note that if no response is provided it is not unlikely that these modules will be removed completely from the upcoming release.

Regards,
Jurriaan

**Comment by ikiril01** [comment]
@jbremer yeah, I've been meaning to refactor the MAEC code for a little while now. What's the ETA for the v2.0 release? We're in the middle of the next release of MAEC, which is slated for September or so. Once that's done, I'd be happy to work on updating the MAEC code. 

Cheers,
Ivan

**Comment by jbremer** [comment]
@ikiril01 ETA for the `2.0` release is the end of September. I think it's easiest to remove said modules now and re-introduce new/improved/up-to-date versions of them in a `2.1` release?

**Comment by ikiril01** [comment]
@jbremer Sounds good - I think that makes sense. I'll make a pull request for the updated module (with MAEC `5.0` support) when ready, for inclusion in a `2.1` release.

**Comment by jbremer** [comment]
Done @ikiril01. Closing this issue now. Please open a new PR (or Issue) when the time is right for you guys - as always we'll be happy to help out.
