### ISSUE TITLE
Cuckoo sandbox database connection error

### ISSUE THREAD

**Issue by deeptakp** [cuckoobox/cuckoo#609]
When I run the command python cuckoo.py at the terminal I'm getting the following error 

  CRITICAL: CuckooDatabaseError: Unable to create or connect to database: (sqlite3.OperationalError) database is locked [SQL: u'PRAGMA table_info("machines_tags")']  

How to solve this issue?

**Comment by SpoonBoy** [comment]
I just cloned a fresh install of cuckoo and i was not able to reproduce your error.
in `conf/cuckoo.conf` can you check what is under the `[database]` ?
if it's empty (which i guess by the sqlite3 error), be sure the cuckoo directory belongs to you and you have write permissions.

**Comment by deeptakp** [comment]
But what editing shall I do in the cuckoo.conf file?

**Comment by deeptakp** [comment]
After properly installing mysql now I'm getting the following error


 Checking for updates...
 Good! You have the latest version available.

/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/compiler.py:572: SAWarning: Can't resolve label reference 'added_on desc'; converting to text() (this warning may be suppressed after 10 occurrences)
  util.ellipses_string(element.element))
2015-08-06 00:51:07,303 [root] CRITICAL: CuckooCriticalError: Unable to bind ResultServer on 192.168.56.101:2042: [Errno 99] Cannot assign requested address

**Comment by jbremer** [comment]
Unfortunately `sqlalchemy` updated with some new warnings that are backwards incompatible. It should still work, but you'll get the `can't resolve label reference` issue.
Other than that the `Cannot assign requested address` error is a known thing and is documented (in our documentation) - just start the VM with VirtualBox once manually and it's resolved.
