### ISSUE TITLE
Performance impact of scheduler lock changes

### ISSUE THREAD

**Issue by Shane-Carr** [cuckoobox/cuckoo#610]
The following two commits:

156b523097977e9c720b5bb779b49c24ddd3558f
db117bc55d975ad53acf0b7d6b9988969699d2cd

seem to have had a huge performance impact.

Depending on machinery, configuration etc the call to machinery.start() can take considerable time.  Holding the global machine_lock throughout basically eliminates all concurrency of the AnalysisManager threads.

If I submit 10 files for analysis and my clients take 10 seconds to revert their snapshot and start, it will take 100 seconds to begin analysis of the 10th file.  Prior to this change, all files would have begun analysis within approximately 10 seconds.

Is there a better way of managing that lock such that the cuckoo performance is not so degraded?

I had to back out the changes as per:

Shane-Carr/cuckoo-modified@cbcf5fd724120801a7de610d7718474b85a5bd65

**Comment by jbremer** [comment]
Hi @Shane-Carr,

Sorry for the delay in replying. Yes, I realize this is one of the side effects of said tweaks. Personally I think the changes are still useful, so we should probably find a way to improve them to also battle your issue. Unfortunately this will probably involve something like rate limiting (as far as I can think of), but I'm more than happy to hear any other thoughts!

**Comment by Shane-Carr** [comment]
Note sure if I understand how introducing rate limiting would be of any benefit.  The key issue is that I have a high throughput application with a large number of clients available.  I am unable to utilise more than a couple of these clients at a time because this lock is being held for so long whilst each client is being acquired.  Much of the parallelism I had from having lots of clients has been lost.

Unless I'm misunderstanding, introducing rate limiting will only limit the number of samples being submitted and not really help at all?

**Comment by jbremer** [comment]
@Shane-Carr Could you please check whether commit 5640d90 fixes your issues? And also whether a default limit of 10 is sufficient or if a bigger limit is required. (Assuming a big machine which is able to handle 20-40 machines in parallel).

**Comment by Shane-Carr** [comment]
Hi @jbremer - this fix seems to work very well.  Happy with a default limit of 10 - it can easily be tweaked to a larger value if required.

Thanks!

**Comment by jbremer** [comment]
Ok, great, thanks for your feedback.
