### ISSUE TITLE
Cuckoo is throwing an error on Submition of malware via API

### ISSUE THREAD

**Issue by Waseem-farooqui** [cuckoobox/cuckoo#613]
I integrated cuckoo with *dionaea* just by adding post url in dionaea configurations but here at cuckoo side I got Server error.
```
    Traceback (most recent call last):
        File "/usr/lib/python2.7/dist-packages/bottle.py", line 856, in _handle
            return route.call(**args)
        File "/usr/lib/python2.7/dist-packages/bottle.py", line 1721, in wrapper
            rv = callback(*a, **ka)
        File "api.py", line 72, in tasks_create_file
            temp_file_path = store_temp_file(data.file.read(), data.filename)
        AttributeError: 'unicode' object has no attribute 'file'
        *.*.*.* - - [13/Aug/2015 12:13:13] "POST /tasks/create/file HTTP/1.1" 500 764
```
If I submit without dionaea it API works fine.
Is there any problem at dionaea side or problem with cuckoo ?
How can I rectify it ?

**Comment by mcpacosy** [comment]
This problem has been fixed already: https://github.com/cuckoobox/cuckoo/commit/4dbdb60edf3d5ba21c1fe1eb81f11290afe0df1c#diff-3d03530109e7e7620d069801fbdbedf5L70

Do you use the current git version? Maybe you should update Cuckoo.

HTH

**Comment by Waseem-farooqui** [comment]
Well I have updated the `api.py` not current version, by submitting via python script its throwing **500** error.
```    Traceback (most recent call last):
	File "/opt/development/report_develop/report/Cuckoo_submit.py", line 27, in <module>
		Submit_Binary()
	File "/opt/development/report_develop/report/Cuckoo_submit.py", line 17, in Submit_Binary
		task_id = json_decoder.decode(request.text)['task_id']
	File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
		obj, end = self.raw_decode(s, idx=_w(s, 0).end())
	File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
		raise ValueError("No JSON object could be decoded")
	ValueError: No JSON object could be decoded```

**Comment by Waseem-farooqui** [comment]
Will you please guide me the fastest and easist way to upgrade the release.
At the official site http://cuckoo.readthedocs.org/en/latest/installation/upgrade/
> The suggested way to upgrade Cuckoo is to start from a fresh setup because it’s easier and faster than migrate your old setup.
Is there any other way to upgrade :(

**Comment by mcpacosy** [comment]
You should check the content of ```request.text``` with a simple ```print request.text``` before line 17. Unfortunately I don't know any other way to upgrade Cuckoo.

**Comment by Waseem-farooqui** [comment]
Will you please tell me the folder where I can find `request.text` with `print request.text` I am getting an **Error**.

**Comment by mcpacosy** [comment]
```request``` is not a folder it's an object in your file ```Cuckoo_submit.py``` file. The error occurs in line 17
```
task_id = json_decoder.decode(request.text)['task_id']
```
Add the line ```print request.text``` above the ```task_id = ...``` line to check the value of ```request.text```. The value should be a JSON string like

```
{
    "task_id" : 1
}
```

It seems that, in your case, there is something wrong with that JSON string...

**Comment by Waseem-farooqui** [comment]
Sorry But 
I have upgraded cuckoo with fresh Installation it work fine with my Submission code but throws **400** in case of Dionaea Submission.

**Comment by mcpacosy** [comment]
Can you please provide more information (source code of your scripts, console output, log files, ...). Otherwise we just can take a wild guess at what causes the errors you report.

**Comment by Waseem-farooqui** [comment]
**This is my code which works fine in submission of Malware.** 

    def Submit_Binary():
            REST_URL = "http://192.168.1.15:8090/tasks/create/file"
            SAMPLE_FILE = "/binaries/1a3e522537a96da07ad0aaf7b2864b11"
            with open(SAMPLE_FILE, "rb") as sample:
                multipart_file = {"file": ("temp_file_name", sample)}
                request = requests.post(REST_URL, files= multipart_file)
                print(request.text)
            json_decoder = json.JSONDecoder()
        
            task_id = json_decoder.decode(request.text)['task_id']
            return task_id

**Here is *Dionaea Honeypot* Submission Section and I don't have any idea of this code**
https://github.com/rep/dionaea/blob/master/modules/python/scripts/submit_http.py

This is the configuration section of Dionaea where I put the url of the submission
     submit_http = {			// ask your submit_http backend provider for needed values
			url = "http://192.168.1.15:8090/tasks/create/file" // the url to send the submission requests to
			email = ""		// optional
			user = "" 		// username (optional)
			pass = ""		// password (optional)
		}

Now in case of Dionaea I got **400**.
I think cuckoo is not supporting the type of request dionaea is sending.

**Comment by mcpacosy** [comment]
Yes I think you are right. You should write your own script to submit the sample.

**Comment by Waseem-farooqui** [comment]
You mean a script in cuckoo that entertain dionaea request ?

**Comment by mcpacosy** [comment]
No, I mean a Dionaea script like this, for example: https://gist.github.com/RamadhanAmizudin/b894d1aa5cd15b212710

**Comment by jbremer** [comment]
As pointed out by @mcpacosy this issue has already been resolved upstream. Please update to the latest version of the `master` branch. Btw, with the `requests` library you can simply do the following to parse the JSON response: `requests.post(...).json()['task_id']`, this will probably work for your use-case.

**Comment by Waseem-farooqui** [comment]
@jbremer I have update it to the latest version  `AttributeError: 'unicode' object has no attribute 'file'` has been removed but my issue still remains.

**Comment by doomedraven** [comment]
i had this today, but it was problem with upload, not cuckoo side problem

**Comment by azfarhalim** [comment]
Can anyone teach me how to integrate dioanea with cuckoo sandbox?

**Comment by Waseem-farooqui** [comment]
@azfarhalim  you have to do some programming for integrating bot of them.

**Comment by Waseem-farooqui** [comment]
Yes I can teach and it depends on the resources you have in my case these are on two different machines.
