### ISSUE TITLE
Sniffer permission denied

### ISSUE THREAD

**Issue by MSaIim** [cuckoobox/cuckoo#617]
Trying to run an analysis and I keep getting "Failed to start sniffer"

    2015-08-16 01:44:40,311 [modules.auxiliary.sniffer] ERROR: Failed to start sniffer (interface=vboxnet0, host=10.1.10.200, dump path=/home/pow/cuckoo/storage/analyses/2/dump.pcap)
    Traceback (most recent call last):
      File "/home/pow/cuckoo/modules/auxiliary/sniffer.py", line 84, in start
        self.proc = subprocess.Popen(pargs)
      File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
        errread, errwrite)
      File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
        raise child_exception
    OSError: [Errno 13] Permission denied

**Comment by jbremer** [comment]
Did you follow the documentation on this matter?

**Comment by MSaIim** [comment]
I didn't see anything in the documentation on why Sniffer would be denied access. I did follow the documentation when installing Cuckoo and the VMs.

**Comment by mcpacosy** [comment]
Make sure you set the right permissions for tcpdump using ```setcap``` as mentioned in the documentation: https://cuckoo.readthedocs.org/en/latest/installation/host/requirements/?highlight=tcpdump#installing-tcpdump

Also verify that you configured the correct network interface that should be monitored in ```auxiliary.conf```:
```
...
# Specify the network interface name on which tcpdump should monitor the
# traffic. Make sure the interface is active.
interface = vboxnet0
...
```
In this case the network interface is ```vboxnet0```.

**Comment by MSaIim** [comment]
I did set permissions during install but I did it again just in case. The network interface is correct and configured right as well. I still get this error:

    2015-08-17 14:33:42,595 [modules.processing.network] ERROR: Unable to open /home/mo/cuckoo/storage/analyses/2/dump_sorted.pcap

**Comment by mcpacosy** [comment]
Does the file `/home/pow/cuckoo/storage/analyses/2/dump_sorted.pcap` exist? If so, what do the permissions look like?

```bash
ls -lh /home/pow/cuckoo/storage/analyses/2/dump_sorted.pcap
```

**Comment by MSaIim** [comment]
No, it does not exist.

**Comment by jbremer** [comment]
Do you have `sort_pcap = on` in `conf/cuckoo.conf`?
Which version of Cuckoo are you running and did you do any changes to it yourself?

**Comment by MSaIim** [comment]
I do have it on in cuckoo.conf. I am running version 1.2 and the the only changes I made was changing the ip addresses to match my server and virtual machines.

**Comment by jbremer** [comment]
This sounds like an issue that can be resolved by reading the documentation again or doing as @mcpacosy mentioned.
