### ISSUE TITLE
Cuckoo always slow on last analyze

### ISSUE THREAD

**Issue by thinhnd8752** [cuckoobox/cuckoo#619]
Hi all. I deployed 2 cuckoo emulator by config similar like this on virtualbox.conf : 
"machines = XP-01,XP-02"
[XP-01]
....
[XP-02]
.....
Everything work ok but if i upload several sample at the same time (Use option "First Available" on web UI). The last sample alway execute quite longer than another. Anyone can give me advice for this?

**Comment by jbremer** [comment]
They are executed one (or in your case two) at a time, so if you submit 10 tasks, the last analysis will only be ran after the earlier 8 or 9 have finished. Is that clear?

**Comment by thinhnd8752** [comment]
Thanks mr jbremer but in my case, after 9 tasks finish, task 10th alway slow

**Comment by gtback** [comment]
How long is it taking, compared to the other ones (based on the start and complete times)? Does it matter if you switch the order of the samples being analyzed (or is it always the same sample)? Is there any information in the logs or on the screen while Cuckoo is running to indicate what component/stage is taking the longest?

**Comment by botherder** [comment]
This ticket is very vague, the problem seems unrelated to the code and the conversation went inactive. Closing.
