### ISSUE TITLE
Virtualbox 5 memory dump command change

### ISSUE THREAD

**Issue by phrewww** [cuckoobox/cuckoo#621]
Virtualbox 5 command for memory dump changed,

https://www.virtualbox.org/manual/ch08.html#vboxmanage-debugvm

VBoxManage debugvm <uuid|vmname> dumpvmcore [--filename=name]

For proper memory dumping 
https://github.com/cuckoobox/cuckoo/blob/master/modules/machinery/virtualbox.py#L206
should read 

label, "dumpvmcore", "--filename", path],

for Virtualbox 5 support

**Comment by l0ngestever** [comment]
I made a fix for this. See this pull request: #628.

**Comment by botherder** [comment]
Those little changes from Oracle that don't make any fucking sense. Thanks for your pull request.
