### ISSUE TITLE
cuckoo web - error while removing analysis results

### ISSUE THREAD

**Issue by pch3** [cuckoobox/cuckoo#634]
When behavior module is enabled but do not produce any output, django web interface fails to remove analysis results:
Internal Server Error: /analysis/remove/1/
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python2.7/dist-packages/django/views/decorators/http.py", line 41, in inner
    return func(request, *args, **kwargs)
  File "/opt/cuckoo/web/analysis/views.py", line 422, in remove
    for process in analysis["behavior"]["processes"]:
KeyError: 'behavior'
[28/Aug/2015 11:01:57] "GET /analysis/remove/1/ HTTP/1.1" 500 223486

**Comment by jbremer** [comment]
Please try that fix :-)

**Comment by pch3** [comment]
I would like to have such response times for my commercial products ;-) 
It works, thx,

**Comment by pch3** [comment]
Hi

Sorry to bother you, but can you reply if logs from agent are stored
anywhere on server side. I noticed those two errors on screen shot and
don't know how to proceed. Sample is taken from malwr.com, but analysis
results are different... working to have the same results.

Cheers.


2015-08-28 11:10 GMT+02:00 Jurriaan Bremer <notifications@github.com>:

**Comment by jbremer** [comment]
The logs from the agent should be visible in `analysis.log` and the `results['debug']['log']` of the JSON report. There's a slim chance this doesn't count for exceptions, but I think those should be in there as well. Please feel free to create a new issue around the exception in your screenshot ;)
