### ISSUE TITLE
analysis log not displayed correctly in webgui

### ISSUE THREAD

**Issue by pch3** [cuckoobox/cuckoo#636]
![screenshot from 2015-08-28 19 56 11](https://cloud.githubusercontent.com/assets/13233057/9553371/dd21f89c-4dbe-11e5-8d8b-a7879ec1bc8c.png)

**Comment by jbremer** [comment]
Ah, yes, its representation was updated not too recently. Let me give it a quick look.

**Comment by pch3** [comment]
I hope you won't hate me for registering 4th issue in two days ;-)

**Comment by jbremer** [comment]
Well, there you go sir ;-) And no worries, please keep the bug reports coming!

**Comment by jbremer** [comment]
Woops, sorry, forgot to mention your nick in the last two bug fixes - next time! ;)

**Comment by pch3** [comment]
NP, I am not doing this for fame ;-)

2015-08-28 20:14 GMT+02:00 Jurriaan Bremer <notifications@github.com>:

**Comment by jbremer** [comment]
Closing this issue as fixed - please reopen or create a new one for any new/other issues ;)
