### ISSUE TITLE
summary -> registry not populated in webgui

### ISSUE THREAD

**Issue by pch3** [cuckoobox/cuckoo#638]
I've noticed summary -> registry (and directories as well) is populated in json report:
       "summary": {
            "directory_created": [
                "c:\\program files (x86)\\safeads\\safeads\\1.3.28.0", 
                "C:\\Program Files (x86)\\safeads\\safeads", 
                "C:\\Program Files (x86)\\safeads\\safeads\\", 
                "C:\\Program Files (x86)\\safeads\\", 
                "C:\\Program Files (x86)\\safeads\\safeads\\1.3.28.0"
            ], 
            "file_opened": [
               this is OK
            ], 
            "regkey_opened": [
                "HKEY_LOCAL_MACHINE\\System\\CurrentControlSet\\Control\\LsaExtensionConfig\\SspiCli", 
                "HKEY_LOCAL_MACHINE\\SOFTWARE\\Wow6432Node\\Microsoft\\Cryptography\\OID\\EncodingType 0\\SchemeDllRetrieveEncodedObjectW", 
...
but not in webgui
![screenshot from 2015-08-28 21 52 11](https://cloud.githubusercontent.com/assets/13233057/9555696/23963f76-4dcf-11e5-91f8-36ec2fb69a04.png)
![screenshot from 2015-08-28 21 52 28](https://cloud.githubusercontent.com/assets/13233057/9555695/23944cfc-4dcf-11e5-8413-339d2eb91ec3.png)

also sometimes empty lines are produced (both in json and wegui):
        "summary": {
            "file_opened": [
                "", 
...
            "mutex": [
                ""
            ],

**Comment by jbremer** [comment]
There's some other fields that should be added, to be done at a later stage.
