### ISSUE TITLE
binary won't execute

### ISSUE THREAD

**Issue by l0ft1369** [cuckoobox/cuckoo#648]
So basically I was trolling my crap-catcher AKA my Email Server's Sinbin and came across an interesting specimen. I went to go put it through CRITs everything looks good. Unzipped as an exe. Verified with a Hexeditor. Went to submit to Cuckoo and here's what I got:

2015-09-21 10:53:19,620 [lib.cuckoo.core.scheduler] ERROR: Analysis failed: The package "modules.packages.exe" start function raised an error: Unable to execute the initial process, analysis aborted.

I've been a support hound in IRC so bremer knows I'm running Mac OS X 10.10 and the VM is a Windows XP Gem. I tried running with -d but that produced output only after the fail. The output was basically complaining that the VM terminated early. Which on the error makes sense. 

I will go back to IRC and continue to vampire support, but I wanted to open an official issue here as well. 

My issue here is how can I debug in the VM and figure out why this exe won't run?

-l0ft

**Comment by botherder** [comment]
Can you provide details on the sample? Architecture? Tested for corruption?

**Comment by jbremer** [comment]
Going to assume this has either been resolved or is not relevant anymore.
