### ISSUE TITLE
Resubmit button

### ISSUE THREAD

**Issue by jbremer** [cuckoobox/cuckoo#653]
Sometimes one will want to resubmit a sample to run it again. There should be a simple button to do this almost automatically - leaving the possibility to modify some of the analysis tasks.
(So a redirect to `/submit` with the `file` part already filled out should be best).

**Comment by KillerInstinct** [comment]
Also a submit button for dropped files :)

**Comment by jpsenior** [comment]
I was just talking about this...  :) great idea
