### ISSUE TITLE
Generic Package, rand_title

### ISSUE THREAD

**Issue by ds108j** [cuckoobox/cuckoo#654]
I don't know if it has already been submitted, you can close this thread if yes.

When I want to submit an analysis with generic package, the cmd prompt can't manage to deal with the random title Cuckoo gives to the window (tested in the virtual machine, and got an error).

It seems that this line 

 rand_title = "".join([chr(randint(0, 128)) for i in xrange(0, randint(1, 10))])

in the file/cuckoo/analyzer/windows/modules/packages can generate title name with characters not cmd compliant.
example : 
"C:\Windows\System32\cmd.exe" /c start /wait H] C:\Users\*****\AppData\Local\Temp\****.exe
Here "H]" generate an error of the cmd prompt.

Thank you for your good work on the project !

**Comment by jbremer** [comment]
No need to close the issue @ds108j :-) Due to the random string generation it probably hit only once every now and then.
Regardless, fixed it for you. Thanks for reporting!

**Comment by ds108j** [comment]
Thanks for fixing! ;)
