### ISSUE TITLE
Incorrect localization of 'mark' types (e.g. mark._type vs mark.type) - signature analysis page

### ISSUE THREAD

**Issue by jpsenior** [cuckoobox/cuckoo#663]
I'm not sure when in the package historythe kewarg 'type' was rneamed to '_type' -- probably to localize variable names, but this is causing an issue in the signatures report.

web/templates/analysis/overview/_signatures.html is looking for 'mark.type' :: but mark.type doesn't exist.  only 'mark._type'.  We can't use variable names with underscores in django templates.

We're trying to coordinate the signatures that are firing with the actual events that caused them.

**Comment by jpsenior** [comment]
I was troubleshooting why all of the table rows were blank in the analysis overview page. I Added a dbeug line {{ mark }} to see what variable naming was:

e.g. one of the IOCs was shown as here:


{u'_type': u'ioc', u'_category': u'file', u'_ioc': u'C:\\Users\\cuckoo\\AppData\\Local\\Microsoft\\Windows\\History\\History.IE5\\index.dat'}

The code is looking for "if mark.type = ioc" -- but "mark.type" isn't valid.  "mark._type" is, so every line for printable output is failing here.

The end result is a completely empty signature results page.

**Comment by jpsenior** [comment]
I was able to ghetto a workaround.

Instead of checkin for 'mark.type' (For example), i am using the get_item template tag that returns a dictionary value:

mark|get_item:"_category"
mark|get_item:"_type"

seems to work much better.

**Comment by jpsenior** [comment]
Source diving. Spamming github. Trying to learn this codebase.

So i'm trying to see if pymongo is inserting that undescore because of a foreign key relationship....



here's the object (truncated) that we're passing through in a template later:

class Signature(object):
     ...
     self.marks = []
     ...
     def mark_call(self, **kwargs):
        """Mark the current call as explanation as to why this signature
        matched."""
        mark = {
            "type": "call",
            "pid": self.pid,
            "cid": self.cid,
            "call": self.call,
            "test": "test",
        }
        mark.update(kwargs)
        self.marks.append(mark)


there's a pymongo class elsewhere in the code that adds results into the mongo database:

the data is being inserted verbosely here:
to_insert = {"pid": process["pid"], "calls": chunk}
chunk_id = self.db.calls.insert(to_insert)

we can see here that the dictionary we're inserting does _not_ have underscores in the column names:




[snip]
    if "behavior" in report and "processes" in report["behavior"]:
            new_processes = []
            for process in report["behavior"]["processes"]:
                new_process = dict(process)

                chunk = []
                chunks_ids = []
                # Loop on each process call.
                for index, call in enumerate(process["calls"]):
                    # If the chunk size is paginate or if the loop is
                    # completed then store the chunk in MongoDB.
                    if len(chunk) == paginate:
                        to_insert = {"pid": process["pid"], "calls": chunk}
                        chunk_id = self.db.calls.insert(to_insert)
                        chunks_ids.append(chunk_id)

[/snip]


When we use this code later for views:

views.py:
import pymongo
from gridfs import GridFS

results_db = pymongo.MongoClient(settings.MONGO_HOST, settings.MONGO_PORT)[settings.MONGO_DB]
fs = GridFS(results_db)



@require_safe
def report(request, task_id):
    report = results_db.analysis.find_one({"info.id": int(task_id)}, sort=[("_id", pymongo.DESCENDING)])

    return render_to_response("analysis/report.html",
                              {"analysis": report, "domainlookups": domainlookups, "iplookups": iplookups},
                              context_instance=RequestContext(request))


and on the template:



{% for signature in analysis.signatures %}
 {% for mark in signature.marks %}

debug {{ mark }} ::
SEEN:
debug {u'_cid': 20762, u'_type': u'call', u'_pid': 1252} ::
EXPECTED:
debug {u'cid': 20762, u'type': u'call', u'pid': 1252} ::

**Comment by KillerInstinct** [comment]
Are you sure this wasn't fixed with:
https://github.com/cuckoobox/cuckoo/commit/a5053c83e20a2148d5c6d9081dca62561eed7eef

**Comment by jbremer** [comment]
It most likely was :) thanks for locating the commit @KillerInstinct

**Comment by jpsenior** [comment]
rm -rf *.pyc .... Code was correct, bytecode was not.
