### ISSUE TITLE
Unmentioned requirements on installation page

### ISSUE THREAD

**Issue by intelemetry** [cuckoobox/cuckoo#664]
Required for pip dependency builds. 

    libffi-dev
    libssl-dev

**Comment by jbremer** [comment]
A whole bunch of other packages should also be downloaded, see also https://github.com/cuckoobox/cuckoo/blob/8b5aad90b9e8aff1f645528ebde3e2fd7e1e1538/utils/setup.sh#L245-L248. Anyone care to update the documentation on this matter? :)

**Comment by botherder** [comment]
We really should keep track of all these dependencies. I wouldn't even be able to say what all of those are for. For the moment I'll update for the ones originally specified in the ticket. The others should be singularly documented.

**Comment by botherder** [comment]
Fixed, closing.
