### ISSUE TITLE
cuckoo -d inform of outdated version 

### ISSUE THREAD

**Issue by GelosSnake** [cuckoobox/cuckoo#672]
pyhon cuckoo -d produce the following warning:
""Outdated! Cuckoo Sandbox version 1.2 is available now." "

**Comment by jbremer** [comment]
@botherder @jekil Please fix the server to handle *2.0-dev*.

**Comment by jbremer** [comment]
Updated Cuckoo to show one is running a development version instead of the supposedly latest version.
