### ISSUE TITLE
Deadlock/Timeout at self.get() / only old agent is running 

### ISSUE THREAD

**Issue by strubbes** [cuckoobox/cuckoo#677]
The line "r = self.get("/")" in start_analysis() in guest.py is not returning and creates a deadlock.

When I'm forcing the use of the old agent by adding the following lines before the self.get():
      
        self.is_old = True
        self.old.start_analysis(options, monitor)
        return

the analysis starts.

- I installed the latest agent inside the guest-VM (Windows 7 X86) and I can ping in both directions and telnet is happy, too.
- I am using the latest cuckoo-sources on an Ubuntu 14.04. Desktop (64bit) host with VirtualBox 5.

Any idea what is going on here?

**Comment by jbremer** [comment]
Hmm, thanks for reporting. The idea behind the `r.get("/")` is to request the `index.html` so to say in order to determine which version of the software is running - the old or the new agent.
However, as this GET request is after waiting for the host to become up-and-running, see also https://github.com/cuckoobox/cuckoo/blob/master/lib/cuckoo/core/guest.py#L379-L380, it should return immediately.
Could you perhaps test if anything happens if you add a timeout, i.e., `r.get("/", timeout=5)` or even better, if you can remove the BFP rules from the tcpdump sniffer https://github.com/cuckoobox/cuckoo/blob/master/modules/auxiliary/sniffer.py#L69-L78 and then share a pcap here? :-)

Thanks!

**Comment by strubbes** [comment]
The test with timeout=5 generated the following log-line:

         ReadTimeout: HTTPConnectionPool(host='192.168.200.1', port=8080): Read timed out. (read timeout=5)

I am a bit confused because my resultserver is running at 192.168.56.1 at interface vboxnet0.

        [lib.cuckoo.core.resultserver] DEBUG: ResultServer running on 192.168.56.1:2042.

192.168.200.1 is the IP of my host connected at interface eth0 ... 

Why does it connect to 192.168.56.101 (guest-IP) and tries now to read from 192.168.200.1 ?

**Comment by jbremer** [comment]
When you apply that patch of yours, with the `is_old = True`, what does the following line say when running?
https://github.com/cuckoobox/cuckoo/blob/master/lib/cuckoo/core/guest.py#L117-L118

**Comment by strubbes** [comment]
It says the following :

        DEBUG: Uploading analyzer to guest (id=Windows_7_32, ip=192.168.56.101)

**Comment by jbremer** [comment]
Just seems odd to me, what about the following statement? https://github.com/cuckoobox/cuckoo/blob/master/lib/cuckoo/core/guest.py#L369-L370
Or actually, uploading your entire `log/cuckoo.log` (that relates to this issue anyway) might be useful as well ;-)

**Comment by strubbes** [comment]
Here is the line :

        INFO: Starting analysis on guest (id=Windows_7_32, ip=192.168.56.101)

and attached the log (didn't accept neither .log nor .txt, so I renamed it to .png)

![log](https://cloud.githubusercontent.com/assets/15686940/10998412/4510b094-8495-11e5-8751-d79f792b9562.png)

Apart from this I've added another log-line inside the self.get()-function printing the url:

          get() : URL (http://192.168.56.101:8000/)

This is the log from a run without my patch forcing the usage of the old agent.
So this was a run that lead to a deadlock.

**Comment by jbremer** [comment]
The IP seems fine to me, no? `192.168.56.101`?

**Comment by strubbes** [comment]
Yes this IP looks good.
 
The more confusing is the result of the log line when I add the timeout=5 ...

         ReadTimeout: HTTPConnectionPool(host='192.168.200.1', port=8080): Read timed out. (read timeout=5)

**Comment by jbremer** [comment]
Please check the pcap because going to another network interface & port doesn't make any sense :-)

**Comment by strubbes** [comment]
I agree on everything you say ... This makes not sense.

Here is the pcap (renamed to png). I removed the lines in sniffer.py to capture the interesting parts, too.

![pcap](https://cloud.githubusercontent.com/assets/15686940/10999093/6f437ae0-849a-11e5-9ee5-6921626bdc0e.png)

**Comment by jbremer** [comment]
There's like, barely any traffic in here at all. Are you sure Agent is running successfully etc?

**Comment by strubbes** [comment]
The agent started and wrote the line (0.0.0.0:8000)

     print("[+] Starting agent on %s:%s ..." % (BIND_IP, BIND_PORT)) 

and the log from the host is the one I already attached. 
Anything else I can provide?

**Comment by jbremer** [comment]
And from the host, if you do "curl 192.168.56.101:8000" it works correctly? (I mean, you get a HTTP response - it'll probably be an error code but that's fine).

**Comment by strubbes** [comment]
Another thing I could mention:

I changed the logging in guest.py
.
.
.
               try:
                socket.create_connection((self.ipaddr, self.port), 1).close()
                break
            except socket.timeout:
                log.debug("%s: not ready yet", self.vmid)
            except socket.error:
                log.debug("%s: not ready yet error", self.vmid)

And as you may have seen inside the log the output changed from "not ready yet" to "no ready yet error" after a few calls. Could this be an incident?

**Comment by strubbes** [comment]
I checked it with 

           telnet 192.168.56.101 8000

and this got a connection and I could communicate to the agent.

Is it worth to give the curl-call another try?

**Comment by jbremer** [comment]
I believe the `socket.error` exception means it can't connect.. To be honest I'm not really sure what's going wrong in your setup.
But do you still have the issue of `192.168.200.1`?

**Comment by strubbes** [comment]
Do you mean the printing in ?

         ReadTimeout: HTTPConnectionPool(host='192.168.200.1', port=8080): Read timed out. (read timeout=5)

Yes.

Can you think of any difference that could lead to the fact that the old-agent is running against the same guest? Or is the difference that the old version is not using sockets at all?

**Comment by strubbes** [comment]
During the writing of my last two lines I got an idea that fixed the problem.

Because of the fact that my old installation (which was the cuckoo-current.tar,gz) was running fine and my new installation (master-branch) not I was not thinking of the proxy.

But this came to my mind when I wrote ( ... not using sockets at all).
After unsetting the environment-variables (http_proxy, https_proxy) inside the shell that starts the cuckoo.py the get() returns.

I am very sorry for opening this issue and wasting your time but you have to admit that the incident of
connecting fine but not communicating was a really ugly one :-(

Maybe you should think about a short advisory inside the documentation or a warning when starting the framework and a proxy has been set.

Apart from that I really appreciate the support you are giving on this framework! 
I am planning to use it intensively for my everyday-work and what I saw until now impressed me a lot!

Good job!

**Comment by jbremer** [comment]
To be honest I didn't even know that Python libraries (i.e., `requests`) look for such environment variables. I personally doubt anyone else will run into this issue, but if you feel like adding it to the documentation, feel free to do a pull request after modifying the respective files; https://github.com/cuckoobox/cuckoo/tree/master/docs/book/src.

Thanks for the feedback - if you have any more issues or feature requests, please let us know :-)
