### ISSUE TITLE
Cannot access machine name in a reporting module

### ISSUE THREAD

**Issue by Mesaph** [cuckoobox/cuckoo#680]
I'm currently trying to write a reporting module that needs to know which machine the sample was executed on.

I am able to access the machine property of the task:
`Config("my_module").get(self.task['machine'])`
However, this only contains the name of the machine if the machine name was specified when submitting the analysis task. Thus, this is of little use to me, as I do not want to force the analysis to be executed on a specific machine.

Is there any other way to get hold of the machine name inside of a reporting module?
If not, would it be possible that the task entry in the db gets updated once the analysis starts to include the name of the selected machine?

**Comment by jbremer** [comment]
It's easiest to take a look at the `report.json` report. I suppose that you'll want to use `results["info"]["machine"]` :-)

**Comment by Mesaph** [comment]
Thanks a lot, that's exactly what I needed :)
