### ISSUE TITLE
http://community.cuckoosandbox.org/ returns internal server error

### ISSUE THREAD

**Issue by simonk9** [cuckoobox/cuckoo#684]
i will hijack this opportunity to a s simple question
when trying to download a report from http://cuckoo:8000/filereport/704/json/
it automatically saves it "704_report.json"

where is the file i can change the auto save name? (i want to saves as md5.json)

**Comment by jbremer** [comment]
What are you doing?

**Comment by simonk9** [comment]
Jurriaan, the 2 things are not related.

1) there is an internal server error when trying to access http://community.cuckoosandbox.org

2) if i already opened an issue for no.1 i thought to ask another question.
i created a manual report and but it saves it as <task_id>_report.extension
i cant find which file contains the definition on the saved report name, i want my report named <md5>.ext

**Comment by jbremer** [comment]
Can you share whatever you made? Still not entirely clear at the moment to me.
@botherder Community down.

**Comment by simonk9** [comment]
@jbremer https://github.com/simonk9/cuckoo-yargen

**Comment by Hyooni** [comment]
Hello everyone,

I'm refreshing this post because the http://community.cuckoosandbox.org page is still down, returning the "500 Internal Server Error".
I was wondering if it was meant to be forever down or if the recovery of the service was just longer than intended ?

**Comment by botherder** [comment]
Closing this ticket cause it's confusing and unrelated to the software itself.
