### ISSUE TITLE
capnproto vs xmlrpclib

### ISSUE THREAD

**Issue by hellok** [cuckoobox/cuckoo#698]
how about capnproto

**Comment by jbremer** [comment]
Thanks for the suggestion. We've started to work towards a new Agent which is not based on xmlrpc anymore but instead features a very basic (but useful) JSON-based REST API.
So I guess that kind of defeats the purpose of having another protocol as well. The Windows Analyzer and Cuckoo Guest helper functionality both support the *new* protocol as well as the old, aside any small bugs that might occur overtime of course.
For now the new Agent can still be found here https://github.com/jbremer/agent

**Comment by jbremer** [comment]
Closing this issue for now. If you have any arguments to re-open, feel free to.
