### ISSUE TITLE
JSON processtree/behavior PID mismatch

### ISSUE THREAD

**Issue by ssobr** [cuckoobox/cuckoo#702]
Looks like the parent pid is being listed as the pid in the behavior section. Here's an example:

"processtree": [
            {
                "pid": 1568, 
                "process_name": "invoice1211_pdf.exe", 
                "first_seen": 1449658424.688, 
                "ppid": 220, 
                "children": [
                    {
                        "pid": 240, 
                        "process_name": "dtayy.exe", 
                        "first_seen": 1449658169.029, 
                        "ppid": 1568, 
                    }
                ]
            }
"behavior": {
        "generic": [
            {
                "first_seen": 1449658424.688, 
                "process_name": "invoice1211_pdf.exe", 
                "pid": 220,
            }, 
            {
                "first_seen": 1449658169.029, 
                "process_name": "dtayy.exe", 
                "pid": 1568,

**Comment by jbremer** [comment]
@rep care to take a look?

**Comment by jbremer** [comment]
Thanks for resolving the issue.
