### ISSUE TITLE
is32bit.exe warning (and analysis failure due timeout)

### ISSUE THREAD

**Issue by lopoc** [cuckoobox/cuckoo#704]
hi mates,

I'm not new to cuckoo, but during my last installation(1.2) and its testing I've faced an issue cannot understand well from what it is triggered.

here is a piece of log found as output of an analysis:
```2015-12-14 21:21:51,361 [analyzer] WARNING: Cannot execute auxiliary module DumpTLSMasterSecrets: Error returned by is32bit: Command '['bin\\is32bit.exe', '-n', 'lsass.exe']' returned non-zero exit status 1```

Let me explain in details what happens; once submitted a sample, the analysis terminate due to timeout.
Jumped into the VM, there is an alert box on the desktop, issued by isbit32.exe, displaying:
```" [-] Error getting access to process: 5! ".```

![alert](https://cloud.githubusercontent.com/assets/701494/11790692/6a8e06a2-a29d-11e5-88b3-cb28618d37eb.png)

Once clicked on ok, the analysis process "wakes up" and terminate providing the expected report.

for any further information about my setup, ask.

**Comment by jbremer** [comment]
Does the Cuckoo Agent have administrator privileges?

**Comment by lopoc** [comment]
actually no.
I've supposed it'd be due to privileges, but tried running manually the command is32bit.exe -n lsass.exe from an administrative command and it raised the same error.

**Comment by jbremer** [comment]
Do you have UAC etc enabled? Tried disabling that?

**Comment by lopoc** [comment]
well, it's working right now, disabling UAC and running the agent as administrator.
thank you.

I'm just wondering how correct is turning off UAC on a machine that should mimic a production one with UAC enabled?

**Comment by jbremer** [comment]
We're happy to talk about workarounds with UAC enabled but at the moment I don't see any easy way to do so - if you do, let us know :-)

**Comment by lopoc** [comment]
got it ;)
 
thank u

**Comment by jbremer** [comment]
Yeah, or even better; a message at runtime `if you see this, please disable UAC` and `if you see this, please run as Administrator`.. :p

**Comment by geek-li** [comment]
Even .I disable the UAC  there is  a same error dialog :(,how to fix this issue

**Comment by TiTi87** [comment]
Same issue here. Cuckoo don't run the any analyse of a zip file :
```
ERROR: Analysis failed: The package "modules.packages.zip" start function encountered an unhandled exception: Error returned by is32bit: Command '['bin\\is32bit.exe', '-f', u'C:\\Users\\user\\AppData\\Local\\Temp\\DOCUME~1.WSF']' returned non-zero exit status 1
```
Same result with --option file=document12.wsf is specified. Tried with  submit.py and the Web-GUI => same result.

UAC is disabled and agent.py is running as administrator. On a Cuckoo-dev version.

Any idea ?

**Comment by Jack28** [comment]
I had the same problem.
It finally stated working after I granted permission for "Debuggen von Programmen" (German. approx. Debugging of Programms) to Administrators.
Similar to https://technet.microsoft.com/en-us/library/cc776977(WS.10).aspx

It required that change and the agent.py to be executed from the Powershell rather than cmd.exe

**Comment by candrei** [comment]
I had to 'relax' the security by disabling UAC via _User Account Control: Run all administrators in Admin Approval Mode_ under _ Local Policies -> Security Options_ via _Local Security Policy_ utility.
